package dev.kof.compiler;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

/**
 * WEB002 — kof.web servidor para o target Nativo.
 *
 * T1: accept loop + resposta 200/hello (commit 89ac0d9)
 * T2: parse METHOD+PATH + match literal → 200/404 (commit 6ad63f8)
 * T3 (em andamento): dispatch do handler lambda via trampolim invoke().
 */
class KofWebNativeE2ETest {

    private Process serverProcess;
    private int serverPort = -1;

    @AfterEach
    void stopServer() {
        if (serverProcess != null) {
            serverProcess.destroy();
            try {
                serverProcess.waitFor(3, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) { }
            serverProcess.destroyForcibly();
            serverProcess = null;
        }
    }

    private static final String SERVER_T1 = """
            main() {
                var app = web.app()
                app.get("/") {
                    return "hello"
                }
                app.listen(PORT)
            }
            """;

    private static final String SERVER_T2 = """
            main() {
                var app = web.app()
                app.get("/hello") {
                    return "ok-matched"
                }
                app.listen(PORT)
            }
            """;

    // ---------------- helpers ----------------

    private static int freePort() throws IOException {
        try (java.net.ServerSocket s = new java.net.ServerSocket(0)) {
            return s.getLocalPort();
        }
    }

    private Process startServer(Path tempDir, String source) throws Exception {
        int port = freePort();
        serverPort = port;
        Path src = tempDir.resolve("App.kf");
        Files.writeString(src, source.replace("PORT", String.valueOf(port)));
        CompilerDriver driver = new CompilerDriver();
        CompilationResult result = driver.compile(src, tempDir.resolve("classes"), Target.NATIVE);
        assertTrue(result.success(), "compile: " + result.diagnostics().getDiagnostics());
        Path binary = tempDir.resolve("classes/Default/Main");
        assertTrue(Files.exists(binary), "native binary should exist");
        ProcessBuilder pb = new ProcessBuilder(binary.toString());
        pb.redirectErrorStream(true);
        Process p = pb.start();
        TestServerFixture.awaitListening(p, port, 100, 50);
        return p;
    }

    private int portFromServer(String source) throws IOException {
        // Generated by test server — guaranteed valid integer
        @SuppressWarnings("NumberFormatException")
        int parsed = Integer.parseInt(source.split("app.listen\\(")[1].split("\\)")[0]);
        return parsed;
    }

    private String httpGet(int port, String path) throws IOException {
        try (Socket s = new Socket("127.0.0.1", port)) {
            s.getOutputStream().write(("GET " + path + " HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n")
                    .getBytes(StandardCharsets.UTF_8));
            s.getOutputStream().flush();
            return new String(s.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    // ---------------- testes ----------------

    @Test
    void nativeServerAcceptsAndResponds200(@TempDir Path tempDir) throws Exception {
        serverProcess = startServer(tempDir, SERVER_T1);
        String resp = httpGet(serverPort, "/");
        assertTrue(resp.startsWith("HTTP/1.1 200") || resp.contains(" 200 "),
                "servidor nativo tem de responder 200 ao GET /: " + resp);
    }

    @Test
    void nativeServerMatchesLiteralRoute(@TempDir Path tempDir) throws Exception {
        int port = freePort();
        Path src = tempDir.resolve("App.kf");
        Files.writeString(src, SERVER_T2.replace("PORT", String.valueOf(port)));
        CompilerDriver driver = new CompilerDriver();
        CompilationResult result = driver.compile(src, tempDir.resolve("classes"), Target.NATIVE);
        assertTrue(result.success(), "compile: " + result.diagnostics().getDiagnostics());
        ProcessBuilder pb = new ProcessBuilder(tempDir.resolve("classes/Default/Main").toString());
        pb.redirectErrorStream(true);
        serverProcess = pb.start();
        TestServerFixture.awaitListening(serverProcess, port, 100, 50);
        String match = httpGet(port, "/hello");
        assertTrue(match.contains("200"), "match: " + match);
        assertTrue(match.endsWith("ok-matched"), "match body: " + match);
        String miss = httpGet(port, "/estanaoexiste");
        assertTrue(miss.contains("404"), "miss: " + miss);
        assertTrue(miss.endsWith("Not Found"), "miss body: " + miss);
    }

    @Test
    void nativeServerDispatchesLambdaHandler(@TempDir Path tempDir) throws Exception {
        int port = freePort();
        Path src = tempDir.resolve("App.kf");
        Files.writeString(src, SERVER_T2.replace("PORT", String.valueOf(port)));
        CompilerDriver driver = new CompilerDriver();
        CompilationResult result = driver.compile(src, tempDir.resolve("classes"), Target.NATIVE);
        assertTrue(result.success(), "compile: " + result.diagnostics().getDiagnostics());
        ProcessBuilder pb = new ProcessBuilder(tempDir.resolve("classes/Default/Main").toString());
        pb.redirectErrorStream(true);
        serverProcess = pb.start();
        TestServerFixture.awaitListening(serverProcess, port, 100, 50);
        String r = httpGet(port, "/hello");
        assertTrue(r.contains("HTTP/1.1 200"), "status: " + r);
        assertTrue(r.endsWith("ok-matched"), "body should come from handler, got: " + r);
    }

    private static final String SERVER_T4 = """
            main() {
                var app = web.app()
                app.post("/echo") {
                    return "got: " + body()
                }
                app.listen(PORT)
            }
            """;

    @Test
    void nativeServerReadsBodyContext(@TempDir Path tempDir) throws Exception {
        int port = freePort();
        Path src = tempDir.resolve("App.kf");
        Files.writeString(src, SERVER_T4.replace("PORT", String.valueOf(port)));
        CompilerDriver driver = new CompilerDriver();
        CompilationResult result = driver.compile(src, tempDir.resolve("classes"), Target.NATIVE);
        assertTrue(result.success(), "compile: " + result.diagnostics().getDiagnostics());
        ProcessBuilder pb = new ProcessBuilder(tempDir.resolve("classes/Default/Main").toString());
        pb.redirectErrorStream(true);
        serverProcess = pb.start();
        TestServerFixture.awaitListening(serverProcess, port, 100, 50);
        try (Socket s = new Socket("127.0.0.1", port)) {
            s.getOutputStream().write("POST /echo HTTP/1.1\r\nHost: x\r\nContent-Length: 5\r\n\r\nhello"
                    .getBytes(StandardCharsets.UTF_8));
            s.getOutputStream().flush();
            String r = new String(s.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
            assertTrue(r.contains("200"), "status: " + r);
            assertTrue(r.endsWith("got: hello"), "body() should echo, got: " + r);
        }
    }
}
