package dev.kof.compiler;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end coverage for the Adam7-interlaced PNG path of the pure-Kof decoder
 * in {@code libs/image/Png.kf} (image-vision pixel slice, provisional
 * {@code Raster} surface).
 *
 * <p>The decoder already handled bit-depth-8 non-interlaced color types 0/2/3/4/6;
 * this slice adds the seven-pass Adam7 sub-image de-interlacing (PNG spec §9),
 * replacing the former {@code IMAGE: interlaced PNG is not supported} refusal.
 * The three fixtures are real interlaced PNGs (generated by ImageMagick and
 * independently byte-validated by Java {@code ImageIO} and PIL): an RGB 20x13
 * (every pass non-empty), an RGBA 13x9 and a grayscale 17x11 where several
 * passes are empty and one is exactly one pixel wide (the stride-0 geometry).
 *
 * <p>Golden = the decoded sample sum and a 24-bit rolling hash, computed from
 * the independent ImageIO/PIL pixels. Proven on JVM + Native x86-64 + riscv64
 * (qemu) + Script; no compiler change.
 */
class PngInterlaceE2ETest {

    private final CompilerDriver driver = new CompilerDriver();

    @TempDir Path tmp;

    private static final String A7_RGB_HEX =
            "89504e470d0a1a0a0000000d49484452000000140000000d08020000015135e99f0000002063"
          + "48524d00007a26000080840000fa00000080e8000075300000ea6000003a98000017709cba51"
          + "3c00000006624b474400ff00ff00ffa0bda7930000000774494d4507ea0a010d153a70664175"
          + "000000764944415428cfe5cc310a80300c40d1a6c6b4d4583a1409a507e8e0d8c1a37804ef7f"
          + "0237c5a10a4e82f096e49380526a0dcb1a1694ad4828120acc369f0be01a679b0f285b119b0f"
          + "30a1bf74ae91ede969064a6e42df825c23a36f79c8306873f79c92236cfa70866eec076dde414a"
          + "8eb479e78fc73bd54b1f2e3d3a0a230000000049454e44ae426082";
    private static final String A7_RGBA_HEX =
            "89504e470d0a1a0a0000000d494844520000000d0000000908060000019e7d96fc0000002063"
          + "48524d00007a26000080840000fa00000080e8000075300000ea6000003a98000017709cba51"
          + "3c00000006624b474400ff00ff00ffa0bda7930000000774494d4507ea0a010d153a70664175"
          + "000000834944415418d36360606060f050d0e8601188b09821a0a0d1c1a82220e2822ac2a123"
          + "e3a32220e202c38c421c5c4a300e0b878e8c0f8780880b073a8791458c4f4d88834b091b86a8"
          + "e4e052c2861939595805b1ea6211e35363e1e052c2c0a44aa861935063e1e0526264e26617e66"
          + "461152405434c636115240d93ae498d144d7075000b361fe751abfba80000000049454e44ae42"
          + "6082";
    private static final String A7_GRAY_HEX =
            "89504e470d0a1a0a0000000d49484452000000110000000b0800000001cb4c094d0000000262"
          + "4b474400ff878fccbf0000000774494d4507ea0a010d153a70664175000000474944415408d7"
          + "6360c8b8c060b18083c1640e938505a38c89898909a394898909938c8c8c0c938c8c8c0c239f"
          + "1414b0c860b21879a10c263e282086c1c8ce8b0658f8a822c207005b84100117d91ccb000000"
          + "0049454e44ae426082";

    private static final String GOLDEN =
              "a7rgb PNG 20x13 ch=3 82160:16191856\n"
            + "a7rgba PNG 13x9 ch=4 37446:5030598\n"
            + "a7gray PNG 17x11 ch=1 24457:3226345";

    @Test
    void interlacedPngOnJvm() throws Exception {
        Path root = tmp.resolve("jvm-pnga7");
        Files.createDirectories(root);
        Path dir = writeFixtures(root.resolve("fixtures"));
        assertEquals(GOLDEN, runJvm(root, probe(dir)));
    }

    @Test
    void interlacedPngOnNativeX86() throws Exception {
        Assumptions.assumeTrue(System.getProperty("os.name").toLowerCase().contains("linux"),
                "Native x86-64 requires the Linux assembler/linker toolchain");
        Path root = tmp.resolve("x86-pnga7");
        Files.createDirectories(root);
        Path dir = writeFixtures(root.resolve("fixtures"));
        assertEquals(GOLDEN, runNativeX86(root, probe(dir)));
    }

    @Test
    void interlacedPngOnNativeRiscv64() throws Exception {
        Assumptions.assumeTrue(has("riscv64-linux-gnu-as", "riscv64-linux-gnu-ld", "qemu-riscv64"),
                "cross riscv64 + qemu absent — skipping (NATIVE002)");
        Path root = tmp.resolve("riscv-pnga7");
        Files.createDirectories(root);
        Path dir = writeFixtures(root.resolve("fixtures"));
        assertEquals(GOLDEN, runCrossCode("riscv64", Target.NATIVE_RISCV64, root, probe(dir)));
    }

    @Test
    void interlacedPngOnScript() throws Exception {
        Path root = tmp.resolve("script-pnga7");
        Files.createDirectories(root);
        Path dir = writeFixtures(root.resolve("fixtures"));
        Files.writeString(root.resolve("Main.kf"), probe(dir));
        KofInterpreter.Result result = withLibrary(root,
                () -> driver.interpret(List.of(root.resolve("Main.kf")), root, new String[0]));
        assertEquals(0, result.exitCode(), "script output: " + result.stdout());
        assertEquals(GOLDEN, result.stdout().strip());
    }

    private Path writeFixtures(Path dir) throws Exception {
        Files.createDirectories(dir);
        Files.write(dir.resolve("a7rgb.png"), hex(A7_RGB_HEX));
        Files.write(dir.resolve("a7rgba.png"), hex(A7_RGBA_HEX));
        Files.write(dir.resolve("a7gray.png"), hex(A7_GRAY_HEX));
        return dir;
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(s.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }

    private static String probe(Path dir) {
        String base = RasterDecodeFixtures.path(dir);
        return "import image.Raster\n"
             + "\n"
             + "String probe(String label, String path) {\n"
             + "    var r = decodeRaster(path)\n"
             + "    var sum = 0 var hash = 0 var i = 0\n"
             + "    while (i < r.samples.length) {\n"
             + "        var v = r.samples[i]\n"
             + "        sum = sum + v\n"
             + "        hash = ((hash << 5) + hash + v) & 16777215\n"
             + "        i = i + 1\n"
             + "    }\n"
             + "    return label + \" \" + r.format + \" \" + r.width + \"x\" + r.height\n"
             + "        + \" ch=\" + r.channels + \" \" + sum + \":\" + hash\n"
             + "}\n\n"
             + "main() {\n"
             + "    println(probe(\"a7rgb\", \"" + base + "/a7rgb.png\"))\n"
             + "    println(probe(\"a7rgba\", \"" + base + "/a7rgba.png\"))\n"
             + "    println(probe(\"a7gray\", \"" + base + "/a7gray.png\"))\n"
             + "}\n";
    }

    private String runJvm(Path root, String code) throws Exception {
        Path source = root.resolve("Main.kf");
        Files.writeString(source, code);
        Path out = root.resolve("out");
        CompilationResult result = withLibrary(root, () -> driver.compile(source, out, Target.JVM));
        assertTrue(result.success(), () -> "compile: " + result.diagnostics().getDiagnostics());
        var stdout = new java.io.ByteArrayOutputStream();
        var previousOut = System.out;
        try {
            System.setOut(new java.io.PrintStream(stdout, true, StandardCharsets.UTF_8));
            try (var loader = new URLClassLoader(
                    new java.net.URL[]{out.toUri().toURL()}, getClass().getClassLoader())) {
                Class.forName("Default.Main", true, loader)
                        .getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            }
        } finally {
            System.setOut(previousOut);
        }
        return stdout.toString(StandardCharsets.UTF_8).strip();
    }

    private String runNativeX86(Path root, String code) throws Exception {
        Files.writeString(root.resolve("Main.kf"), code);
        Path out = root.resolve("out");
        withLibrary(root, () -> {
            CompilationResult result = driver.compile(root.resolve("Main.kf"), out, Target.NATIVE);
            assertTrue(result.success(),
                    () -> "native compile: " + result.diagnostics().getDiagnostics());
            return null;
        });
        return runBinary(out.resolve("Default/Main"));
    }

    private String runCrossCode(String arch, Target target, Path root, String code) throws Exception {
        Files.writeString(root.resolve("Main.kf"), code);
        Path out = root.resolve("out");
        withLibrary(root, () -> {
            CompilationResult result = driver.compile(root.resolve("Main.kf"), out, target);
            assertTrue(result.success(),
                    () -> arch + " compile: " + result.diagnostics().getDiagnostics());
            return null;
        });
        Path binary = out.resolve("Default/Main");
        assertTrue(Files.isRegularFile(binary), arch + " binary must exist");
        ProcessBuilder pb = NativeRiscv64E2ETest.qemu(arch, binary);
        pb.redirectErrorStream(true);
        Process process = pb.start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8)
                .replace("\r\n", "\n").strip();
        assertEquals(0, process.waitFor(), arch + " output: " + output);
        return output;
    }

    private static String runBinary(Path binary) throws Exception {
        Process process = new ProcessBuilder(binary.toString())
                .redirectErrorStream(true).start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8)
                .replace("\r\n", "\n").strip();
        assertEquals(0, process.waitFor(), "native output: " + output);
        return output;
    }

    private static boolean has(String... cmds) {
        for (String c : cmds) {
            try {
                Process p = new ProcessBuilder("sh", "-c", "command -v " + c)
                        .redirectErrorStream(true).start();
                if (p.waitFor() != 0) return false;
            } catch (Exception e) {
                return false;
            }
        }
        return true;
    }

    private <T> T withLibrary(Path root, PngA7Action<T> action) throws Exception {
        Path lib = root.resolve("kof-install/lib/kof-libs/image");
        Path sourceRoot = libraryRoot();
        try (var files = Files.walk(sourceRoot)) {
            for (Path source : files.filter(Files::isRegularFile).toList()) {
                Path destination = lib.resolve(sourceRoot.relativize(source));
                Files.createDirectories(destination.getParent());
                Files.copy(source, destination, StandardCopyOption.REPLACE_EXISTING);
            }
        }
        String previous = System.getProperty("kof.install.dir");
        System.setProperty("kof.install.dir", root.resolve("kof-install").toString());
        try {
            return action.get();
        } finally {
            if (previous == null) System.clearProperty("kof.install.dir");
            else System.setProperty("kof.install.dir", previous);
        }
    }

    @FunctionalInterface
    private interface PngA7Action<T> {
        T get() throws Exception;
    }

    private static Path libraryRoot() {
        Path workingDirectory = Path.of("").toAbsolutePath().normalize();
        Path fromRepository = workingDirectory.resolve("libs/image");
        if (Files.isDirectory(fromRepository)) return fromRepository;
        Path fromModule = workingDirectory.resolve("../libs/image").normalize();
        if (Files.isDirectory(fromModule)) return fromModule;
        throw new IllegalStateException("libs/image not found from " + workingDirectory);
    }
}
