package dev.kof.compiler;

import java.util.List;

/**
 * JsEmitter — renders the JsIr (JavaScript AST) as ECMAScript source text.
 *
 * The emitter knows nothing about Kof IR: it only prints JS AST nodes.
 * Output targets ECMAScript 2022+ modules (ESM). No legacy syntax is emitted.
 */
final class JsEmitter {

    private final StringBuilder sb = new StringBuilder();
    private int indent = 0;
    /** Linhas dos cabeçalhos de função gerada → linha Kof (source map). */
    private final List<JsIr.JsFunctionLine> functionLines = new java.util.ArrayList<>();

    /** Mapeamento linha-gerada → linha-Kof para o source map V3. */
    public List<JsIr.JsFunctionLine> functionLines() {
        return functionLines;
    }

    /** Próxima linha a ser emitida (1-based) — usada no source map. */
    private int lineNo = 1;

    String emit(JsIr.JsModule module) {
        sb.setLength(0);
        indent = 0;
        functionLines.clear();
        lineNo = 1;
        line("// Generated by the Kof compiler — KofJS backend. Do not edit.");
        line("// Target: ECMAScript 2022+ (ES modules)");
        line("// Module: " + module.name());
        line("");
        if (!module.runtimeImports().isEmpty()) {
            line("import { " + String.join(", ", module.runtimeImports()) + " } from './kof-runtime.mjs';");
        }
        if (!module.ioRuntimeImports().isEmpty()) {
            line("import { " + String.join(", ", module.ioRuntimeImports()) + " } from './kof-runtime-io.mjs';");
        }
        if (!module.runtimeImports().isEmpty() || !module.ioRuntimeImports().isEmpty()) {
            line("");
        }
        for (JsIr.JsClass cls : module.classes()) {
            emitClass(cls);
            line("");
        }
        for (JsIr.JsFunction fn : module.functions()) {
            emitFunction(fn);
            line("");
        }
        for (JsIr.JsStatement stmt : module.statements()) {
            emitStatement(stmt);
            line("");
        }
        return sb.toString();
    }

    private void emitClass(JsIr.JsClass cls) {
        line("class " + cls.name() + (cls.superName() == null || cls.superName().isEmpty() ? "" : " extends " + cls.superName()) + " {");
        indent++;
        for (JsIr.JsField field : cls.fields()) {
            String prefix = field.isStatic() ? "static " : "";
            line(prefix + field.name() + (field.initializer() == null ? "" : " = " + field.initializer()) + ";");
        }
        if (!cls.fields().isEmpty()) line("");
        for (JsIr.JsFunction method : cls.methods()) {
            emitFunction(method);
        }
        indent--;
        line("}");
    }

    private void emitFunction(JsIr.JsFunction fn) {
        if (fn.kofLine() != null && fn.kofLine() > 0) {
            functionLines.add(new JsIr.JsFunctionLine(
                    fn.name(), lineNo, fn.kofLine()));
        }
        StringBuilder header = new StringBuilder();
        if (fn.isTopLevel()) {
            if (fn.isAsync() && !fn.isConstructor()) header.append("async ");
            header.append("function ");
        } else if (!fn.isConstructor()) {
            if (fn.isStatic()) header.append("static ");
            if (fn.isAsync()) header.append("async ");
        }
        if (fn.isConstructor()) {
            header.append("constructor(").append(String.join(", ", fn.parameters())).append(")");
        } else {
            header.append(fn.name()).append("(").append(String.join(", ", fn.parameters())).append(")");
        }
        line(header.toString() + " {");
        indent++;
        for (JsIr.JsStatement stmt : fn.body()) {
            emitStatement(stmt);
        }
        indent--;
        line("}");
    }

    private void emitStatement(JsIr.JsStatement stmt) {
        if (stmt instanceof JsIr.JsExprStmt es) {
            line(expr(es.expression()) + ";");
        } else if (stmt instanceof JsIr.JsVarDecl vd) {
            line((vd.isConst() ? "const " : "let ") + vd.name()
                    + (vd.initializer() == null ? "" : " = " + expr(vd.initializer())) + ";");
        } else if (stmt instanceof JsIr.JsAssign as) {
            line(as.target() + " = " + expr(as.value()) + ";");
        } else if (stmt instanceof JsIr.JsReturn r) {
            line(r.value() == null ? "return;" : "return " + expr(r.value()) + ";");
        } else if (stmt instanceof JsIr.JsBreak) {
            line("break;");
        } else if (stmt instanceof JsIr.JsContinue) {
            line("continue;");
        } else if (stmt instanceof JsIr.JsThrow t) {
            line("throw " + expr(t.value()) + ";");
        } else if (stmt instanceof JsIr.JsBlock b) {
            line("{");
            indent++;
            for (JsIr.JsStatement s : b.statements()) emitStatement(s);
            indent--;
            line("}");
        } else if (stmt instanceof JsIr.JsIf i) {
            line("if (" + expr(i.condition()) + ") {");
            indent++;
            for (JsIr.JsStatement s : i.thenBranch()) emitStatement(s);
            indent--;
            if (i.elseBranch() == null || i.elseBranch().isEmpty()) {
                line("}");
            } else {
                line("} else {");
                indent++;
                for (JsIr.JsStatement s : i.elseBranch()) emitStatement(s);
                indent--;
                line("}");
            }
        } else if (stmt instanceof JsIr.JsWhile w) {
            if (w.isDoWhile()) {
                line("do {");
                indent++;
                for (JsIr.JsStatement s : w.body()) emitStatement(s);
                indent--;
                line("} while (" + expr(w.condition()) + ");");
            } else {
                line("while (" + expr(w.condition()) + ") {");
                indent++;
                for (JsIr.JsStatement s : w.body()) emitStatement(s);
                indent--;
                line("}");
            }
        } else if (stmt instanceof JsIr.JsFor f) {
            StringBuilder init = new StringBuilder();
            for (int i = 0; i < f.init().size(); i++) {
                if (i > 0) init.append(" ");
                if (f.init().get(i) instanceof JsIr.JsVarDecl vd) {
                    init.append(vd.isConst() ? "const " : "let ").append(vd.name())
                            .append(vd.initializer() == null ? "" : " = " + expr(vd.initializer())).append(";");
                } else if (f.init().get(i) instanceof JsIr.JsExprStmt es) {
                    init.append(expr(es.expression())).append(";");
                } else if (f.init().get(i) instanceof JsIr.JsAssign as) {
                    init.append(as.target()).append(" = ").append(expr(as.value())).append(";");
                }
            }
            StringBuilder update = new StringBuilder();
            for (int i = 0; i < f.update().size(); i++) {
                if (i > 0) update.append(", ");
                if (f.update().get(i) instanceof JsIr.JsExprStmt es) {
                    update.append(expr(es.expression()));
                } else if (f.update().get(i) instanceof JsIr.JsAssign as) {
                    update.append(as.target()).append(" = ").append(expr(as.value()));
                } else if (f.update().get(i) instanceof JsIr.JsVarDecl vd) {
                    update.append(vd.name()).append(" = ").append(expr(vd.initializer()));
                }
            }
            StringBuilder head = new StringBuilder("for (");
            head.append(init.isEmpty() ? ";" : init);
            if (f.condition() != null) {
                head.append(" ").append(expr(f.condition()));
            }
            head.append("; ").append(update).append(") {");
            line(head.toString());
            indent++;
            for (JsIr.JsStatement s : f.body()) emitStatement(s);
            indent--;
            line("}");
        } else if (stmt instanceof JsIr.JsForIn fi) {
            line("for (let " + fi.varName() + " of " + expr(fi.collection()) + ") {");
            indent++;
            for (JsIr.JsStatement s : fi.body()) emitStatement(s);
            indent--;
            line("}");
        } else if (stmt instanceof JsIr.JsSwitch sw) {
            line("switch (" + expr(sw.subject()) + ") {");
            indent++;
            for (JsIr.JsSwitchCase c : sw.cases()) {
                line("case " + expr(c.value()) + ":");
                indent++;
                for (JsIr.JsStatement s : c.body()) emitStatement(s);
                line("break;");
                indent--;
            }
            if (sw.defaultCase() != null && !sw.defaultCase().isEmpty()) {
                line("default:");
                indent++;
                for (JsIr.JsStatement s : sw.defaultCase()) emitStatement(s);
                indent--;
            }
            indent--;
            line("}");
        } else if (stmt instanceof JsIr.JsTry t) {
            line("try {");
            indent++;
            for (JsIr.JsStatement s : t.tryBody()) emitStatement(s);
            indent--;
            if (t.catches() != null) {
                for (JsIr.JsCatchClause c : t.catches()) {
                    line("} catch (" + c.param() + ") {");
                    indent++;
                    for (JsIr.JsStatement s : c.body()) emitStatement(s);
                    indent--;
                }
            }
            if (t.finallyBody() != null && !t.finallyBody().isEmpty()) {
                line("} finally {");
                indent++;
                for (JsIr.JsStatement s : t.finallyBody()) emitStatement(s);
                indent--;
            }
            line("}");
        }
    }

    private String expr(JsIr.JsExpression e) {
        if (e instanceof JsIr.JsNumber n) return n.text();
        if (e instanceof JsIr.JsString s) return stringLiteral(s.value());
        if (e instanceof JsIr.JsNull) return "null";
        if (e instanceof JsIr.JsIdentifier i) return i.name();
        if (e instanceof JsIr.JsThis) return "this";
        if (e instanceof JsIr.JsBinary b) return "(" + expr(b.left()) + " " + b.operator() + " " + expr(b.right()) + ")";
        if (e instanceof JsIr.JsUnary u) {
            String op = u.operator();
            if ("typeof".equals(op)) return "(typeof " + expr(u.operand()) + ")";
            return "(" + op + expr(u.operand()) + ")";
        }
        if (e instanceof JsIr.JsCall c) {
            StringBuilder args = new StringBuilder();
            for (int i = 0; i < c.arguments().size(); i++) {
                if (i > 0) args.append(", ");
                args.append(expr(c.arguments().get(i)));
            }
            return expr(c.callee()) + "(" + args + ")";
        }
        if (e instanceof JsIr.JsNew n) {
            StringBuilder args = new StringBuilder();
            for (int i = 0; i < n.arguments().size(); i++) {
                if (i > 0) args.append(", ");
                args.append(expr(n.arguments().get(i)));
            }
            return "new " + expr(n.callee()) + "(" + args + ")";
        }
        if (e instanceof JsIr.JsMember m) return expr(m.target()) + "." + m.name();
        if (e instanceof JsIr.JsIndex i) return expr(i.target()) + "[" + expr(i.index()) + "]";
        if (e instanceof JsIr.JsConditional c) {
            return "(" + expr(c.condition()) + " ? " + expr(c.thenExpr()) + " : " + expr(c.elseExpr()) + ")";
        }
        if (e instanceof JsIr.JsSequence seq) {
            StringBuilder parts = new StringBuilder();
            for (JsIr.JsExpression p : seq.expressions()) {
                if (!parts.isEmpty()) parts.append(", ");
                parts.append(expr(p));
            }
            if (!parts.isEmpty()) parts.append(", ");
            parts.append(expr(seq.value()));
            return "(" + parts + ")";
        }
        if (e instanceof JsIr.JsArray a) {
            return "new Array(" + expr(a.size()) + ").fill(" + a.fill() + ")";
        }
        if (e instanceof JsIr.JsObjectLiteral o) {
            StringBuilder parts = new StringBuilder();
            for (JsIr.JsObjectEntry entry : o.entries()) {
                if (!parts.isEmpty()) parts.append(", ");
                parts.append(stringLiteral(entry.key())).append(": ").append(expr(entry.value()));
            }
            return "{" + parts + "}";
        }
        if (e instanceof JsIr.JsInstanceOf io) return "(" + expr(io.operand()) + " instanceof " + io.typeName() + ")";
        if (e instanceof JsIr.JsAssignExpr ae) return "(" + ae.target() + " = " + expr(ae.value()) + ")";
        if (e instanceof JsIr.JsArrow ar) {
            return "(" + String.join(", ", ar.parameters()) + ") => " + expr(ar.body());
        }
        if (e instanceof JsIr.JsAwait aw) return "(await " + expr(aw.operand()) + ")";
        throw new IllegalStateException("unknown JS expression: " + e);
    }

    private String stringLiteral(String value) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : value.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                case '\b' -> sb.append("\\b");
                case '\f' -> sb.append("\\f");
                default -> {
                    if (c < 0x20 || c == 0x2028 || c == 0x2029) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

    private void line(String text) {
        if (text.isEmpty()) {
            sb.append('\n');
            lineNo++;
            return;
        }
        sb.append("    ".repeat(indent));
        sb.append(text);
        sb.append('\n');
        lineNo++;
    }
}