package dev.kof.compiler;

/** kof-runtime.mjs — núcleo (helpers neutros de plataforma). */
final class JsRuntimeCore {
    private JsRuntimeCore() {
    }

    static final String CORE_RUNTIME = """
            // KofJS core runtime — platform-neutral helpers.
            // Generated by the Kof compiler (KofJS backend).
            // This module is not a VM: it only provides operations that
            // JavaScript does not represent directly.

            if (typeof document === "undefined") {
                function kofMakeEl(tag) {
                    return {
                        tagName: String(tag).toUpperCase(),
                        id: null,
                        className: "",
                        textContent: "",
                        children: [],
                        parentNode: null,
                        style: {},
                        appendChild(child) {
                            if (child && child.parentNode) child.parentNode.removeChild(child);
                            child.parentNode = this;
                            this.children.push(child);
                            return child;
                        },
                        removeChild(child) {
                            const i = this.children.indexOf(child);
                            if (i >= 0) { this.children.splice(i, 1); child.parentNode = null; }
                            return child;
                        },
                        remove() { if (this.parentNode) this.parentNode.removeChild(this); },
                        addEventListener(type, fn) { this._handlers = this._handlers || {}; (this._handlers[type] = this._handlers[type] || []).push(fn); }
                    };
                }
                const kofRoot = kofMakeEl("div");
                kofRoot.id = "kof-root";
                const kofElements = { "kof-root": kofRoot };
                const kofHead = kofMakeEl("head");
                const kofHtml = kofMakeEl("html");
                kofHtml.appendChild(kofHead);
                globalThis.document = {
                    title: "",
                    head: kofHead,
                    documentElement: kofHtml,
                    createElement(tag) { return kofMakeEl(tag); },
                    getElementById(id) { return kofElements[id] || null; }
                };
                globalThis.window = globalThis;
                globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
            }

            function kofEscapeHtml(s) {
                return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
                        .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
            }

            function kofSerialize(node) {
                if (!node) return "";
                const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
                let attrs = "";
                if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
                if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
                const kids = Array.from(node.children || []);
                const inner = kids.map(kofSerialize).join("");
                const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
                return "<" + tag + attrs + ">" + content + "</" + tag + ">";
            }

            export function kofUiSerializeHtml() {
                const root = document.getElementById("kof-root");
                if (!root) return "";
                const html = "<!DOCTYPE html>\\n<html>\\n<head>\\n<meta charset=\\"utf-8\\">\\n"
                        + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\\n"
                        + "</head>\\n<body>\\n" + kofSerialize(root) + "\\n</body>\\n</html>\\n";
                globalThis.kof__uiRootHtml = html;
                return html;
            }

            export function kofPrintln(x) {
                console.log(x);
            }

            let kofLogLevel = 1; // default "info": 0 debug, 1 info, 2 warn, 3 error, 4 off
            try {
                const lv = (process.env.KOF_LOG_LEVEL || "info").trim().toLowerCase();
                if (lv === "debug") kofLogLevel = 0;
                else if (lv === "warn") kofLogLevel = 2;
                else if (lv === "error") kofLogLevel = 3;
                else if (lv === "off") kofLogLevel = 4;
            } catch (e) { /* non-node env: keep default */ }

            export function kofLogDebug(msg) { if (kofLogLevel <= 0) console.log(String(msg)); }
            export function kofLogInfo(msg)  { if (kofLogLevel <= 1) console.log(String(msg)); }
            export function kofLogWarn(msg)  { if (kofLogLevel <= 2) (console.warn || console.log)(String(msg)); }
            export function kofLogError(msg) { if (kofLogLevel <= 3) (console.error || console.log)(String(msg)); }

            export function kofUiWindowNew(title) {
                if (typeof document === "undefined") {
                    return -1;
                }
                kofUiInjectTheme();
                const root = document.getElementById("kof-root");
                if (!root) {
                    return -1;
                }
                if (typeof window.__kofWindows === "undefined") {
                    window.__kofWindows = {};
                }
                const id = Object.keys(window.__kofWindows).length + 1;
                const winEl = document.createElement("div");
                winEl.className = "kof-window";
                window.__kofWindows[id] = winEl;
                document.title = title;
                root.appendChild(winEl);
                return id;
            }

            // Kof UI theme — the same Dracula/VSCode aesthetic in every host
            // (browser, webview, KofWebHost): one Kof program, one look.
            function kofUiInjectTheme() {
                if (typeof document === "undefined") return;
                if (document.getElementById("kof-theme")) return;
                const style = document.createElement("style");
                style.id = "kof-theme";
                style.textContent = [
                    ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
                    "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
                    "html, body { margin:0; height:100%; overflow:hidden; }",
                    "body { background:var(--bg); color:var(--fg); font-family:",
                    '  "Cascadia Code", "Fira Code", Consolas, Menlo, monospace; }',
                    ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
                    "  white-space:pre-wrap; padding:2px 0; }"
                ].join("\\n");
                (document.head || document.documentElement).appendChild(style);
            }

            export function kofUiWindowSetTitle(window, title) {
                if (typeof document !== "undefined") {
                    document.title = title;
                }
            }

            export function kofUiWindowTitle(window) {
                return typeof document !== "undefined" ? document.title : "";
            }

            export function kofUiWindowBind(win, label) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (!winEl) return;
                // Component Core: a component binds under the window and mounts
                // (view + onMount) — lifecycle is automatic.
                const comp = kofUiComponents.get(label);
                if (comp) {
                    if (comp.el) winEl.appendChild(comp.el);
                    kofUiComponentMount(label);
                    return;
                }
                const nodes = globalThis.window && globalThis.window.__kofNodes;
                const node = nodes && nodes[label];
                if (node) {
                    winEl.appendChild(node);
                }
            }

            export function kofUiWindowShow(window) {
                kofUiSerializeHtml();
            }

            export function kofUiWindowSetSize(window, width, height) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    winEl.style.width = width + "px";
                    winEl.style.height = height + "px";
                }
                try {
                    if (typeof window.resizeTo === "function") {
                        window.resizeTo(width, height);
                    }
                } catch (e) {
                    // resizeTo is blocked on some hosts; the CSS sizing above
                    // still constrains the window content.
                }
            }

            export function kofUiWindowClose(window) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    if (winEl.parentNode) {
                        winEl.parentNode.removeChild(winEl);
                    }
                    delete window.__kofWindows[window];
                }
            }

            export function kofUiWindowSetTheme(window, theme) {
                if (typeof document === "undefined") {
                    return;
                }
                const root = document.getElementById("kof-root");
                if (!root) {
                    return;
                }
                const colors = theme
                        ? { background: 0x121212FF, text: 0xFFFFFFFF }
                        : { background: 0xFFFFFFFF, text: 0x000000FF };
                root.style.backgroundColor = kofUiColorToCss(colors.background);
                root.style.color = kofUiColorToCss(colors.text);
            }
            """;

}
