package dev.kof.compiler;

/** kof-runtime-io.mjs — plataforma (fs/console). */
final class JsRuntimeIo {
    private JsRuntimeIo() {
    }

    static final String IO_RUNTIME = """
            // KofJS platform runtime — filesystem/console operations for the
            // KofJS target. Generated by the Kof compiler (KofJS backend).
            //
            // This module delegates to the kof_platform object exposed by the
            // Kof process (dev.kof.runtime.KofJsRunner) when Kof executes the
            // generated module with its embedded JavaScript engine. The
            // generated .mjs files are standard ES2022+ modules and do not
            // depend on Node.js or any other external runtime.
            //
            // In a browser (kof-webview / web deployment) there is no
            // kof_platform host object: console operations fall back to the
            // browser console and IO operations report a clear error instead
            // of a ReferenceError.

            const kof_platform = globalThis.kof_platform || new Proxy({ print(x) { console.log(String(x)); } }, {
                get(t, prop) {
                    if (prop in t) return t[prop];
                    return function () {
                        throw new Error("kof.io: " + String(prop) + " is not available in the browser");
                    };
                }
            });

            export function kofPrint(x) {
                kof_platform.print(String(x));
            }

            export function kofArgs() {
                if (kof_platform.args) {
                    return kof_platform.args();
                }
                if (typeof process !== "undefined" && process.argv) {
                    return process.argv.slice(2);
                }
                return [];
            }

            export function kofProcessRun(program, args) {
                const result = kof_platform.processRun(program, args);
                return {
                    stdout: result.stdout,
                    stderr: result.stderr,
                    exitCode: result.exitCode
                };
            }

            export function kofProcessExit(code) {
                // sentinel: o runner converte no exit code do processo
                throw { __kof_exit__: code };
            }

            export function kofReadLine() {
                return kof_platform.readLine();
            }

            export function kofReadFile(p) {
                return kof_platform.readFile(p);
            }

            export function kofWriteFile(p, content) {
                return kof_platform.writeFile(p, content);
            }

            export function kofIoFileExists(p) {
                return kof_platform.fileExists(p);
            }

            export function kofIoFileIsFile(p) {
                return kof_platform.fileIsFile(p);
            }

            export function kofIoFileIsDir(p) {
                return kof_platform.fileIsDir(p);
            }

            export function kofIoReadText(p) {
                return kof_platform.readText(p);
            }

            export function kofIoWriteText(p, content) {
                return kof_platform.writeText(p, content);
            }

            export function kofIoAppendText(p, content) {
                return kof_platform.appendText(p, content);
            }

            export function kofIoReadBytes(p) {
                return kof_platform.readBytes(p);
            }

            export function kofIoWriteBytes(p, bytes) {
                return kof_platform.writeBytes(p, bytes);
            }

            export function kofIoAppendBytes(p, bytes) {
                return kof_platform.appendBytes(p, bytes);
            }

            export function kofIoDelete(p) {
                return kof_platform.delete(p);
            }

            export function kofIoFileSize(p) {
                return kof_platform.fileSize(p);
            }

            export function kofIoFileName(p) {
                return kof_platform.fileName(p);
            }

            export function kofIoPathParent(p) {
                return kof_platform.pathParent(p);
            }

            export function kofIoPathFileName(p) {
                return kof_platform.pathFileName(p);
            }

            export function kofIoPathExtension(p) {
                return kof_platform.pathExtension(p);
            }

            export function kofIoPathNormalize(p) {
                return kof_platform.pathNormalize(p);
            }

            export function kofIoPathResolve(base, child) {
                return kof_platform.pathResolve(base, child);
            }

            export function kofIoPathIsAbsolute(p) {
                return kof_platform.pathIsAbsolute(p);
            }

            export function kofIoPathToAbsolute(p) {
                return kof_platform.pathToAbsolute(p);
            }

            export function kofIoDirCreate(p) {
                return kof_platform.dirCreate(p);
            }

            export function kofIoDirCreateDirs(p) {
                return kof_platform.dirCreateDirs(p);
            }

            export function kofIoDirDelete(p) {
                return kof_platform.dirDelete(p);
            }

            export function kofIoDirList(p) {
                return kof_platform.dirList(p);
            }
            """;

}
