import re, unicodedata
def slug(t):
    s=t.replace('## ','').lower().replace('`','').replace('*','')
    s=s.replace('\u2014','').replace('\u2705','').replace('\u274c','').replace('\U0001f534','')
    s=re.sub(r'[^\w\- ]','',s); s=re.sub(r'\s','-',s.strip())
    return ''.join(c for c in unicodedata.normalize('NFD',s) if unicodedata.category(c)!='Mn')
EN_HEAD="## \u00a7613 \u2014 the \u00a7612 fix (#772 native MAGIC-box dispatch) shipped a zero-regression violation: its numeric/boolean-wrapper `valueOf` box branch now wins where the stringify sugar owned the value \u2014 native JSON of an int column prints the empty string, AV1 aarch64 SIGSEGVs, VP8 riscv64 reports array-index-out-of-bounds, the ORM native x86-64 oracle contract breaks, and the pruned hello runtime grew back from <110 to 126 syms \u2014 \U0001f534 RED (found 06/10 by the 0.6.0 cut-readiness audit, owner = native-backend lane / \u00a7612 author; issues #772-reopened + #773)"
EN_BODY='''

**Symptom (measured 06/10, battery bisect on `lab`):** same 5-class battery, parent `36f72695e` = 147 run / **0F** -> `1d9415d00` (the \u00a7612 fix) = **5F deterministic** -> tip `fd0ff7cb9` unchanged. (1) `KofDbE2ETest.nativeSqliteRoundtrip`: expected `{"id":7,"name":"Nativa"}` but was `{"id":"","name":"Nativa"}` — int->string value-of prints EMPTY on native; (2) `Av1CoeffsE2ETest.av1CoeffsOnNativeAarch64`: qemu SIGSEGV (139); (3) `Vp8RasterE2ETest.vp8RasterOnNativeRiscv64`: `Runtime error: array index out of bounds` (exit 1) — value corruption on cross; (4) `KofOrmE2ETest.crossNativeF1aDeleteAllCountMatchX86Oracle`: the D-DB-GAPS oracle (drop -> count 0 / deleteAll false) mismatches; (5) `ArtifactSizeTest.helloX86NativeSizeWithinBaseline`: hello grew `<110` -> **126 syms** (S-3 prune undone — `wrapperValueOfBoxFn` emits `kof_box_*` at every numeric-wrapper `valueOf` site, reviving slices the pruner dropped).

**Root (measured, from the \u00a7612 diff):** `NativeOpHelpers.wrapperValueOfBoxFn` + `NativeX86ValueOf` + `NativeRiscvCrossOps` route a numeric/boolean-wrapper `valueOf(int)` to the MAGIC box (`kof_box_*`) for the narrowed-arg consumer — but on native `valueOf` is ALSO the stringify sugar (`"" + i`, JSON of an int column, `println`); the stringifier now receives a MAGIC-box handle instead of digits and prints empty / reads it as a pointer/index (the AV1/VP8/ORM cross corruption). The dispatch between stringify-sugar and box must be re-scoped so only the narrowed-int-arg-to-primitive-consumer gets the MAGIC box (the #772 face \u00a7612 was asked to fix).

**Boundary:** regression record only — bisect evidence, repro faces, suspected root; the fix belongs to the \u00a7612 author lane (native-backend), tracked by #772 (reopened) + #773. `lab` is NOT stable for the 0.6.0 cut (`D-LAB-STABILITY`): suite-report SLIPS until these five faces + the \u00a7612 fix faces are all green.
'''
pt_head="## \u00a7613 \u2014 a corre\u00e7\u00e3o \u00a7612 (despacho MAGIC-box nativo, #772) embarcou uma viola\u00e7\u00e3o de zero-regress\u00e3o: o ramo de box de `valueOf` de wrapper num\u00e9rico/booleano agora vence onde a cuca de stringify dono do valor \u2014 JSON nativo de coluna int imprime a string vazia, AV1 aarch64 SIGSEGVa, VP8 riscv64 d\u00e1 \u00edndice de array fora de limites, o or\u00e1culo ORM x86-64 nativo quebra e o hello podado voltou de <110 para 126 syms \u2014 \U0001f534 RED (achado 06/10 pela auditoria de prontid\u00e3o do corte 0.6.0, dona = lane native-backend / autora do \u00a7612; issues #772-reaberta + #773)"
pt_body='''

**Sintoma (medido 06/10, bisect de bateria no `lab`):** mesma bateria de 5 classes, pai `36f72695e` = 147 executados / **0F** -> `1d9415d00` (a corre\u00e7\u00e3o \u00a7612) = **5F determin\u00edsticas** -> tip `fd0ff7cb9` inalterado. (1) `KofDbE2ETest.nativeSqliteRoundtrip`: esperado `{"id":7,"name":"Nativa"}`, obtido `{"id":"","name":"Nativa"}` \u2014 value-of int->string imprime VAZIO no nativo; (2) `Av1CoeffsE2ETest.av1CoeffsOnNativeAarch64`: SIGSEGV no qemu (139); (3) `Vp8RasterE2ETest.vp8RasterOnNativeRiscv64`: `Runtime error: array index out of bounds` (exit 1) \u2014 corrup\u00e7\u00e3o de valor no cross; (4) `KofOrmE2ETest.crossNativeF1aDeleteAllCountMatchX86Oracle`: o or\u00e1culo D-DB-GAPS (drop -> count 0 / deleteAll false) diverge; (5) `ArtifactSizeTest.helloX86NativeSizeWithinBaseline`: hello cresceu `<110` -> **126 syms** (a poda S-3 desfeita \u2014 `wrapperValueOfBoxFn` emite `kof_box_*` em todo s\u00edtio de `valueOf` de wrapper num\u00e9rico, ressuscitando fatias que o podador cortava).

**Causa-raiz (medida, a partir do diff \u00a7612):** `NativeOpHelpers.wrapperValueOfBoxFn` + `NativeX86ValueOf` + `NativeRiscvCrossOps` rota um `valueOf(int)` de wrapper num\u00e9rico/booleano para a MAGIC box (`kof_box_*`) para o consumidor de arg narrowed \u2014 mas no nativo `valueOf` \u00e9 TAMB\u00c9M a cuca de stringify (`"" + i`, JSON de coluna int, `println`); o stringifier agora recebe um handle de MAGIC box em vez dos d\u00edgitos e imprime vazio / o l\u00ea como ponteiro/\u00edndice (a corrup\u00e7\u00e3o AV1/VP8/ORM no cross). O despacho entre a cuca de stringify e o box precisa ser re-escopado para que s\u00f3 o consumidor primitivo do arg narrowed receba a MAGIC box (a face #772 que o \u00a7612 foi chamado a corrigir).

**Limite:** registro de regress\u00e3o apenas \u2014 evid\u00eancia de bisect, faces do repro, causa raiz suspeita; a corre\u00e7\u00e3o pertence \u00e0 lane autora do \u00a7612 (native-backend), rastreada por #772 (reaberta) + #773. O `lab` N\u00c3O est\u00e1 est\u00e1vel para o corte 0.6.0 (`D-LAB-STABILITY`): suite-report SLIPS at\u00e9 estas cinco faces + as faces da corre\u00e7\u00e3o \u00a7612 estarem todas verdes.
'''
anchor=slug(pt_head)
en=open('docs/bugs-and-gaps/known-bugs.md',encoding='utf-8').read()
open('docs/bugs-and-gaps/known-bugs.md','w',encoding='utf-8').write(en.rstrip()+'\n'+EN_HEAD+EN_BODY+'\n\n<!-- pt-switch --> **PT:** [\u00a7613 (pt_BR)](known-bugs.pt_BR.md#'+anchor+')\n')
pt=open('docs/bugs-and-gaps/known-bugs.pt_BR.md',encoding='utf-8').read()
open('docs/bugs-and-gaps/known-bugs.pt_BR.md','w',encoding='utf-8').write(pt.rstrip()+'\n'+pt_head+pt_body+'\n')
print("§613 written; checking known-bugs gate...")
