package dev.kof.compiler.jvm;

import java.util.List;

/**
 * Runtime do kof.orm (entity + orm.*) — gerado no KofRuntime junto com o
 * JvmRuntime. Separado num arquivo próprio porque o constant pool do
 * javac limita cada classe: o ORM + MongoDB num único text block
 * estourariam o limite de 65535 bytes por string.
 */
public final class JvmOrmRuntime {

    private JvmOrmRuntime() {}

    static String source() {
        return """
""" + """
                // ── kof.orm — ORM sobre kof.db (JDBC + MongoDB) ────────
                // O schema é gerado pelo compilador a partir da entity
                // (nunca reflection para descobrir schema); o mapping de
                // records reutiliza o binding do JSON.

                private static final class OrmField {
                    final String name;
                    final String type;
                    final boolean generated;
                    final boolean unique;
                    OrmField(String name, String type, boolean generated, boolean unique) {
                        this.name = name;
                        this.type = type;
                        this.generated = generated;
                        this.unique = unique;
                    }
                }

                private static java.util.List<OrmField> kof_orm_schema(String schema) {
                    java.util.List<OrmField> out = new java.util.ArrayList<>();
                    for (String part : schema.split(",")) {
                        String[] bits = part.split(":");
                        boolean generated = false;
                        boolean unique = false;
                        for (int i = 2; i < bits.length; i++) {
                            if ("generated".equals(bits[i])) generated = true;
                            if ("unique".equals(bits[i])) unique = true;
                        }
                        out.add(new OrmField(bits[0], bits[1], generated, unique));
                    }
                    return out;
                }

                private static String kof_orm_dialect(String id) throws Exception {
                    if (kof_mongo_id(id)) return "mongo";
                    String product = kof_db_conn(id).getMetaData().getDatabaseProductName().toLowerCase();
                    if (product.contains("mysql") || product.contains("mariadb")) return "mysql";
                    if (product.contains("postgresql")) return "postgres";
                    if (product.contains("oracle")) return "oracle";
                    if (product.contains("sqlite")) return "sqlite";
                    return "standard";
                }

                private static String kof_orm_sql_type(String type, String dialect) {
                    return switch (type) {
                        case "int" -> "sqlite".equals(dialect) ? "INTEGER" : "INT";
                        case "long" -> "sqlite".equals(dialect) ? "INTEGER" : "BIGINT";
                        case "bool" -> "mysql".equals(dialect) ? "TINYINT(1)" : "BOOLEAN";
                        case "double" -> "DOUBLE";
                        case "float" -> "REAL";
                        default -> "VARCHAR(255)";
                    };
                }

                private static String kof_orm_pk_ddl(String dialect) {
                    return switch (dialect) {
                        case "mysql" -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
                        case "sqlite" -> "INTEGER PRIMARY KEY AUTOINCREMENT";
                        default -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                    };
                }

                private static String kof_orm_q(String ident, String dialect) {
                    // identificadores sempre quotados — nomes de entidades
                    // podem ser palavras reservadas do SQL (ex.: user)
                    if ("mysql".equals(dialect)) {
                        return "`" + ident + "`";
                    }
                    return "\\"" + ident + "\\"";
                }

                private static int kof_orm_pkIndex(java.util.List<OrmField> fields) {
                    for (int i = 0; i < fields.size(); i++) {
                        if (fields.get(i).generated) return i;
                    }
                    return 0;
                }

                public static boolean kof_orm_create(String id, String table, String schema) throws Exception {
                    if (kof_mongo_id(id)) {
                        // coleções do MongoDB são criadas sob demanda
                        return true;
                    }
                    java.util.List<OrmField> fields = kof_orm_schema(schema);
                    String dialect = kof_orm_dialect(id);
                    StringBuilder ddl = new StringBuilder("CREATE TABLE IF NOT EXISTS ").append(kof_orm_q(table, dialect)).append(" (");
                    for (int i = 0; i < fields.size(); i++) {
                        if (i > 0) ddl.append(", ");
                        OrmField f = fields.get(i);
                        if (f.generated) {
                            ddl.append(kof_orm_q(f.name, dialect)).append(' ').append(kof_orm_pk_ddl(dialect));
                        } else {
                            ddl.append(kof_orm_q(f.name, dialect)).append(' ').append(kof_orm_sql_type(f.type, dialect));
                            if (f.unique) ddl.append(" UNIQUE");
                        }
                    }
                    ddl.append(')');
                    return kof_db_execute(id, ddl.toString()) >= 0;
                }

                private static java.lang.reflect.Method kof_mongo_method(Class<?> type, String name, int arity,
                                                                           Class<?>... argTypes) {
                    // escolhe a sobrecarga compatível com os argumentos
                    // (ex.: find(Bson) vs find(Class)); variantes com
                    // ClientSession são evitadas
                    java.lang.reflect.Method fallback = null;
                    for (java.lang.reflect.Method m : type.getMethods()) {
                        if (m.getName().equals(name) && m.getParameterCount() == arity) {
                            if (m.getParameterCount() > 0
                                    && m.getParameterTypes()[0].getName().contains("ClientSession")) {
                                continue;
                            }
                            boolean compatible = true;
                            for (int i = 0; i < arity && i < argTypes.length; i++) {
                                if (!m.getParameterTypes()[i].isAssignableFrom(argTypes[i])) {
                                    compatible = false;
                                    break;
                                }
                            }
                            if (compatible) {
                                m.setAccessible(true);
                                return m;
                            }
                            fallback = m;
                        }
                    }
                    if (fallback != null) {
                        fallback.setAccessible(true);
                        return fallback;
                    }
                    throw new IllegalStateException("MongoDB method not found: " + name + "/" + arity);
                }

                public static Object kof_orm_save(String id, Object obj, String table, String schema) throws Exception {

                    String dialect = kof_orm_dialect(id);                    java.util.List<OrmField> fields = kof_orm_schema(schema);
                    int pkIndex = kof_orm_pkIndex(fields);
                    java.lang.reflect.RecordComponent[] comps = obj.getClass().getRecordComponents();
                    Object[] values = new Object[comps.length];
                    for (int i = 0; i < comps.length; i++) {
                        values[i] = comps[i].getAccessor().invoke(obj);
                    }
                    Object pk = values[pkIndex];
                    if (kof_mongo_id(id)) {
                        // upsert por _id (o id é fornecido pela aplicação)
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_eq("_id", pk);
                        Object doc = kof_mongo_values(comps, values);
                        Class<?> optsType = Class.forName("com.mongodb.client.model.ReplaceOptions");
                        Object opts = optsType.getConstructor().newInstance();
optsType.getMethod("upsert", boolean.class).invoke(opts, true);
                         kof_mongo_method(coll.getClass(), "replaceOne", 3, filter.getClass(), doc.getClass(), optsType).invoke(coll, filter, doc, opts);
                         return obj;
                    }
                    boolean pkIsNumeric = pk instanceof Number
                            || "int".equals(fields.get(pkIndex).type)
                            || "long".equals(fields.get(pkIndex).type);
                    long pkLong = pk instanceof Number n ? n.longValue()
                            : (pk == null ? 0L : 0L);
                    if (pk == null || (pkIsNumeric && pkLong == 0L)) {
                        // INSERT sem a PK — o banco gera o id
                        StringBuilder cols = new StringBuilder();
                        StringBuilder marks = new StringBuilder();
                        java.util.List<Object> binds = new java.util.ArrayList<>();
                        for (int i = 0; i < fields.size(); i++) {
                            if (i == pkIndex) continue;
                            if (cols.length() > 0) { cols.append(", "); marks.append(", "); }
                            cols.append(kof_orm_q(fields.get(i).name, dialect));
                            marks.append('?');
                            binds.add(values[i]);
                        }
                        try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                                "INSERT INTO " + kof_orm_q(table, dialect) + " (" + cols + ") VALUES (" + marks + ")",
                                java.sql.Statement.RETURN_GENERATED_KEYS)) {
                            for (int i = 0; i < binds.size(); i++) ps.setObject(i + 1, binds.get(i));
                            ps.executeUpdate();
                            try (java.sql.ResultSet keys = ps.getGeneratedKeys()) {
                                if (keys.next()) {
                                    values[pkIndex] = keys.getObject(1);
                                }
                            }
                        }
                        return kof_orm_newInstance(obj.getClass(), values);
                    }
                    // UPDATE
                    StringBuilder sets = new StringBuilder();
                    java.util.List<Object> binds = new java.util.ArrayList<>();
                    for (int i = 0; i < fields.size(); i++) {
                        if (i == pkIndex) continue;
                        if (sets.length() > 0) sets.append(", ");
                        sets.append(kof_orm_q(fields.get(i).name, dialect)).append(" = ?");
                        binds.add(values[i]);
                    }
                    binds.add(pk);
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "UPDATE " + kof_orm_q(table, dialect) + " SET " + sets + " WHERE "
                                    + kof_orm_q(fields.get(pkIndex).name, dialect) + " = ?")) {
                        for (int i = 0; i < binds.size(); i++) ps.setObject(i + 1, binds.get(i));
                        if (ps.executeUpdate() > 0) {
                            return obj;
                        }
                    }
                    // PK não-numérica ou id inexistente: INSERT (upsert-like)
                    StringBuilder cols = new StringBuilder();
                    StringBuilder marks = new StringBuilder();
                    java.util.List<Object> insertBinds = new java.util.ArrayList<>();
                    for (int i = 0; i < fields.size(); i++) {
                        if (cols.length() > 0) { cols.append(", "); marks.append(", "); }
                        cols.append(kof_orm_q(fields.get(i).name, dialect));
                        marks.append('?');
                        insertBinds.add(values[i]);
                    }
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "INSERT INTO " + kof_orm_q(table, dialect) + " (" + cols + ") VALUES (" + marks + ")")) {
                        for (int i = 0; i < insertBinds.size(); i++) ps.setObject(i + 1, insertBinds.get(i));
                        ps.executeUpdate();
                    }
                    return obj;
                }

                private static Object kof_orm_newInstance(Class<?> type, Object[] values) throws Exception {
                    java.lang.reflect.Constructor<?> ctor = type.getDeclaredConstructors()[0];
                    ctor.setAccessible(true);
                    // o reflection não faz widening: o generated key do
                    // MariaDB/MySQL vem como BigDecimal — normaliza para
                    // o tipo declarado (long/int)
                    java.lang.Class<?>[] params = ctor.getParameterTypes();
                    for (int i = 0; i < values.length && i < params.length; i++) {
                        if (values[i] == null) continue;
                        if (params[i] == long.class && values[i] instanceof Number) {
                            values[i] = ((Number) values[i]).longValue();
                        } else if (params[i] == int.class && values[i] instanceof Number) {
                            values[i] = ((Number) values[i]).intValue();
                        }
                    }
                    return ctor.newInstance(values);
                }

                public static Object kof_orm_find(String id, Object key, String table, String schema, String className) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_eq("_id", key);
                        Object iter = kof_mongo_method(coll.getClass(), "find", 1, filter.getClass()).invoke(coll, filter);
                        Object doc = kof_mongo_method(iter.getClass(), "first", 0).invoke(iter);
                        if (doc == null) return null;
                        return kof_json_bind(Class.forName(className), (java.util.Map<String, Object>) doc);
                    }
                    java.util.List<OrmField> fields = kof_orm_schema(schema);
                    String pk = fields.get(kof_orm_pkIndex(fields)).name;
                    java.util.ArrayList<Object> rows = kof_db_query1(id,
                            "SELECT * FROM " + kof_orm_q(table, dialect) + " WHERE " + kof_orm_q(pk, dialect) + " = ?", key, className);
                    return rows.isEmpty() ? null : rows.get(0);
                }

                public static java.util.ArrayList<Object> kof_orm_all(String id, String table, String schema, String className) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        return kof_mongo_query_all(id, table, className);
                    }
                    return kof_db_query0(id, "SELECT * FROM " + kof_orm_q(table, dialect), className);
                }

                private static java.util.ArrayList<Object> kof_mongo_query_all(String id, String table, String className) throws Exception {
                    Object coll = kof_mongo_coll(id, table);
                    Object iter = kof_mongo_method(coll.getClass(), "find", 0).invoke(coll);
                    // FindIterable.into(target) preenche a coleção passada —
                    // o argumento é a instância, não o Class.
                    java.util.List<?> raw = (java.util.List<?>) kof_mongo_method(iter.getClass(), "into", 1,
                            java.util.Collection.class).invoke(iter, new java.util.ArrayList<>());
                    java.util.ArrayList<Object> out = new java.util.ArrayList<>();
                    Class<?> target = Class.forName(className);
                    for (Object d : raw) {
                        out.add(kof_json_bind(target, (java.util.Map<String, Object>) d));
                    }
                    return out;
                }

                public static java.util.ArrayList<Object> kof_orm_where(String id, String field, Object value, String table, String schema, String className) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_eq(field, value);
                        Object iter = kof_mongo_method(coll.getClass(), "find", 1, filter.getClass()).invoke(coll, filter);
                        // FindIterable.into(target) preenche a coleção passada —
                        // o argumento é a instância, não o Class.
                        java.util.List<?> raw = (java.util.List<?>) kof_mongo_method(iter.getClass(), "into", 1,
                                java.util.Collection.class).invoke(iter, new java.util.ArrayList<>());
                        java.util.ArrayList<Object> out = new java.util.ArrayList<>();
                        Class<?> target = Class.forName(className);
                        for (Object d : raw) {
                            out.add(kof_json_bind(target, (java.util.Map<String, Object>) d));
                        }
                        return out;
                    }
                    return kof_db_query1(id, "SELECT * FROM " + kof_orm_q(table, dialect) + " WHERE "
                            + kof_orm_q(field, dialect) + " = ?", value, className);
                }

                public static long kof_orm_count(String id, String table, String schema) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object n = kof_mongo_method(coll.getClass(), "countDocuments", 0).invoke(coll);
                        return ((Number) n).longValue();
                    }
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "SELECT COUNT(*) FROM " + kof_orm_q(table, dialect))) {
                        try (java.sql.ResultSet rs = ps.executeQuery()) {
                            return rs.next() ? rs.getLong(1) : 0L;
                        }
                    }
                }

                public static boolean kof_orm_migrate(String id, String name, String sql) throws Exception {

                    String dialect = kof_orm_dialect(id);                    // tabela de histórico — uma migração roda uma única vez
                    kof_db_execute(id, "CREATE TABLE IF NOT EXISTS "
                            + kof_orm_q("kof_migrations", dialect) + " ("
                            + kof_orm_q("name", dialect) + " VARCHAR(255) PRIMARY KEY, "
                            + kof_orm_q("applied_at", dialect) + " BIGINT)");
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "SELECT COUNT(*) FROM " + kof_orm_q("kof_migrations", dialect)
                                    + " WHERE " + kof_orm_q("name", dialect) + " = ?")) {
                        ps.setString(1, name);
                        try (java.sql.ResultSet rs = ps.executeQuery()) {
                            if (rs.next() && rs.getLong(1) > 0) {
                                return true; // já aplicada
                            }
                        }
                    }
                    if (kof_db_execute(id, sql) < 0) {
                        return false;
                    }
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "INSERT INTO " + kof_orm_q("kof_migrations", dialect) + " ("
                                    + kof_orm_q("name", dialect) + ", " + kof_orm_q("applied_at", dialect) + ") VALUES (?, ?)")) {
                        ps.setString(1, name);
                        ps.setLong(2, System.currentTimeMillis());
                        ps.executeUpdate();
                    }
                    return true;
                }

                public static boolean kof_orm_delete(String id, Object key, String table, String schema) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_eq("_id", key);
                        Object r = kof_mongo_method(coll.getClass(), "deleteOne", 1, filter.getClass()).invoke(coll, filter);
                        return ((Number) kof_mongo_method(r.getClass(), "getDeletedCount", 0).invoke(r)).longValue() > 0;
                    }
                    java.util.List<OrmField> fields = kof_orm_schema(schema);
                    String pk = fields.get(kof_orm_pkIndex(fields)).name;
                    return kof_db_execute1(id, "DELETE FROM " + kof_orm_q(table, dialect) + " WHERE "
                            + kof_orm_q(pk, dialect) + " = ?", key) >= 0;
                }

                public static long kof_orm_count_where(String id, String field, Object value,
                        String table, String schema) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_eq(field, value);
                        Object n = kof_mongo_method(coll.getClass(), "countDocuments", 1,
                                filter.getClass()).invoke(coll, filter);
                        return ((Number) n).longValue();
                    }
                    try (java.sql.PreparedStatement ps = kof_db_conn(id).prepareStatement(
                            "SELECT COUNT(*) FROM " + kof_orm_q(table, dialect) + " WHERE "
                                    + kof_orm_q(field, dialect) + " = ?")) {
                        ps.setObject(1, value);
                        try (java.sql.ResultSet rs = ps.executeQuery()) {
                            return rs.next() ? rs.getLong(1) : 0L;
                        }
                    }
                }

                public static boolean kof_orm_delete_all(String id, String table, String schema) throws Exception {

                    String dialect = kof_orm_dialect(id);                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object r = kof_mongo_method(coll.getClass(), "deleteMany", 1,
                                kof_mongo_eq("_id", "").getClass().getInterfaces()[0]).invoke(coll,
                                kof_mongo_empty_filter());
                        return ((Number) kof_mongo_method(r.getClass(), "getDeletedCount", 0).invoke(r)).longValue() > 0;
                    }
                    return kof_db_execute(id, "DELETE FROM " + kof_orm_q(table, dialect)) >= 0;
                }

                private static Object kof_mongo_empty_filter() throws Exception {
                    Class<?> filters = Class.forName("com.mongodb.client.model.Filters");
                    return filters.getMethod("ne", String.class, Object.class).invoke(null, "_id", null);
                }

                public static java.util.ArrayList<Object> kof_orm_where_op(String id, String field, String op,
                        Object value, String table, String schema, String className) throws Exception {

                    String dialect = kof_orm_dialect(id);                    // whitelist: o operador é um literal do usuário, nunca
                    // concatenado direto no SQL
                    String sqlOp = switch (op) {
                        case ">", "<", ">=", "<=", "!=", "LIKE" -> op;
                        case "==" -> "=";
                        default -> throw new IllegalArgumentException("ORM operator not allowed: " + op);
                    };
                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object filter = kof_mongo_op(field, op, value);
                        Object iter = kof_mongo_method(coll.getClass(), "find", 1, filter.getClass()).invoke(coll, filter);
                        java.util.List<?> raw = (java.util.List<?>) kof_mongo_method(iter.getClass(), "into", 1,
                                java.util.Collection.class).invoke(iter, new java.util.ArrayList<>());
                        java.util.ArrayList<Object> out = new java.util.ArrayList<>();
                        Class<?> target = Class.forName(className);
                        for (Object d : raw) {
                            out.add(kof_json_bind(target, (java.util.Map<String, Object>) d));
                        }
                        return out;
                    }
                    return kof_db_query1(id, "SELECT * FROM " + kof_orm_q(table, dialect) + " WHERE "
                            + kof_orm_q(field, dialect) + " " + sqlOp + " ?", value, className);
                }

                public static boolean kof_orm_save_all(String id, java.util.List<?> items, String table, String schema)
                        throws Exception {
                    // batch: cada item segue o mesmo caminho do save
                    // (upsert por PK; no MongoDB, replaceOne com upsert)
                    for (Object item : items) {
                        kof_orm_save(id, item, table, schema);
                    }
                    return true;
                }

                public static java.util.ArrayList<Object> kof_orm_page(String id, Object limit, Object offset,
                        String table, String schema, String className) throws Exception {

                    String dialect = kof_orm_dialect(id);                    int lim = ((Number) limit).intValue();
                    int off = ((Number) offset).intValue();
                    if (kof_mongo_id(id)) {
                        Object coll = kof_mongo_coll(id, table);
                        Object iter = kof_mongo_method(coll.getClass(), "find", 0).invoke(coll);
                        Object it2 = kof_mongo_method(iter.getClass(), "skip", 1, int.class).invoke(iter, off);
                        Object it3 = kof_mongo_method(it2.getClass(), "limit", 1, int.class).invoke(it2, lim);
                        java.util.List<?> raw = (java.util.List<?>) kof_mongo_method(it3.getClass(), "into", 1,
                                java.util.Collection.class).invoke(it3, new java.util.ArrayList<>());
                        java.util.ArrayList<Object> out = new java.util.ArrayList<>();
                        Class<?> target = Class.forName(className);
                        for (Object d : raw) {
                            out.add(kof_json_bind(target, (java.util.Map<String, Object>) d));
                        }
                        return out;
                    }
                    return kof_db_query2(id, "SELECT * FROM " + kof_orm_q(table, dialect)
                            + " LIMIT ? OFFSET ?", lim, off, className);
                }

""";
    }
}
