package dev.kof.compiler.jvm;

/**
 * 
 * Extraído de JvmRuntime.sourceCore (REFACTOR-500 Fase 5) — fragmento do
 * source do KofRuntime gerado; a concatenação preserva conteúdo byte-a-byte.
 */
public final class JvmRuntimeJson {

    private JvmRuntimeJson() {}

    static String source(String decoders) {
        return """
            package dev.kof.runtime;

            import java.lang.reflect.Field;
            import java.lang.reflect.Modifier;
            import java.lang.reflect.RecordComponent;
            import java.util.ArrayList;
            import java.util.LinkedHashMap;
            import java.util.List;
            import java.util.Map;

            /**
             * JSON helpers for the JVM target of the Kof compiler.
             * Generated by JvmRuntime at build time; the native target has its
             * own assembly implementations of the same functions.
             */
            public final class KofRuntime {

                private KofRuntime() {}

                public static String kof_json_encode_int(int value) {
                    return Integer.toString(value);
                }

                public static String kof_json_encode_long(long value) {
                    return Long.toString(value);
                }

                public static String kof_json_encode_bool(int value) {
                    return value != 0 ? "true" : "false";
                }

                public static String kof_json_encode_float(float value) {
                    if (Float.isNaN(value) || Float.isInfinite(value)) return "null";
                    return Float.toString(value);
                }

                public static String kof_json_encode_double(double value) {
                    if (Double.isNaN(value) || Double.isInfinite(value)) return "null";
                    return Double.toString(value);
                }

                public static String kof_json_encode_string(String value) {
                    if (value == null) return "null";
                    StringBuilder sb = new StringBuilder(value.length() + 2);
                    sb.append('"');
                    for (int i = 0; i < value.length(); i++) {
                        char c = value.charAt(i);
                        switch (c) {
                            case '"' -> sb.append("\\\\\\"");
                            case '\\\\' -> sb.append("\\\\\\\\");
                            case '\\n' -> sb.append("\\\\n");
                            case '\\r' -> sb.append("\\\\r");
                            case '\\t' -> sb.append("\\\\t");
                            default -> {
                                if (c < 0x20) {
                                    sb.append("\\\\u");
                                    String hex = Integer.toHexString(c);
                                    sb.append("0".repeat(4 - hex.length()));
                                    sb.append(hex);
                                } else {
                                    sb.append(c);
                                }
                            }
                        }
                    }
                    sb.append('"');
                    return sb.toString();
                }

                public static String kof_json_encode_list(List<?> list, int tag) {
                    StringBuilder sb = new StringBuilder("[");
                    for (int i = 0; i < list.size(); i++) {
                        if (i > 0) sb.append(',');
                        Object e = list.get(i);
                        switch (tag) {
                            case 1 -> sb.append(kof_json_encode_string((String) e));
                            // §512 (26/09): o slot JVM de List<Bool> guarda BOOLEAN
                            // (não Integer) — o cast antigo estourava CCE; x86 lê 0/1 cru.
                            case 2 -> sb.append(kof_json_encode_bool(((Boolean) e).booleanValue() ? 1 : 0));
                            default -> sb.append(kof_json_encode(e));
                        }
                    }
                    sb.append(']');
                    return sb.toString();
                }

                public static String kof_json_encode_array(Object array) {
                    StringBuilder sb = new StringBuilder("[");
                    int length = java.lang.reflect.Array.getLength(array);
                    for (int i = 0; i < length; i++) {
                        if (i > 0) sb.append(',');
                        sb.append(kof_json_encode(java.lang.reflect.Array.get(array, i)));
                    }
                    return sb.append(']').toString();
                }

                public static String kof_json_encode(Object value) {
                    if (value == null) return "null";
                    if (value instanceof String s) return kof_json_encode_string(s);
                    if (value instanceof Integer i) return kof_json_encode_int(i);
                    if (value instanceof Long l) return kof_json_encode_long(l);
                    if (value instanceof Boolean b) return kof_json_encode_bool(b ? 1 : 0);
                    if (value instanceof Float f) return kof_json_encode_float(f);
                    if (value instanceof Double d) return kof_json_encode_double(d);
                    if (value instanceof List<?> l) {
                        StringBuilder sb = new StringBuilder("[");
                        for (int i = 0; i < l.size(); i++) {
                            if (i > 0) sb.append(',');
                            sb.append(kof_json_encode(l.get(i)));
                        }
                        return sb.append(']').toString();
                    }
                    if (value.getClass().isArray()) return kof_json_encode_array(value);
                    if (value instanceof Map<?, ?> m) return kof_json_encode_map(m, 0);
                    // D-SECRETS P2 (redação forçada, camada runtime): um Secret que
                    // chega ao serializador por qualquer caminho (inclusive
                    // reflexão/interop) vira a forma REDIGIDA — nunca os campos.
                    if (value instanceof Secret s) return kof_json_encode_string(s.toString());
                    return kof_json_encode_object(value);
                }

                // §106 (decisão 2b, 13/09): Map -> objeto JSON com chaves SORTED
                // (determinismo > ordem de insercao). Map nao e objeto de campos:
                // refletir getDeclaredFields sobre HashMap crasha
                // (InaccessibleObjectException) — itera entries com chaves ordenadas.
                // §106 (2b): assinatura com tag do valor (mesma do encode_list:
                // 0=int, 1=string, 2=bool) — o call-site baixa (Map,I).
                public static String kof_json_encode_map(Map<?, ?> m, int tag) {
                    StringBuilder sb = new StringBuilder("{");
                    java.util.SortedSet<String> keys = new java.util.TreeSet<>();
                    for (Object k : m.keySet()) keys.add(String.valueOf(k));
                    boolean first = true;
                    for (String k : keys) {
                        if (!first) sb.append(',');
                        first = false;
                        sb.append(kof_json_encode_string(k));
                        sb.append(':');
                        sb.append(encodeByTag(m.get(k), tag));
                    }
                    return sb.append('}').toString();
                }

                private static String encodeByTag(Object v, int tag) {
                    if (tag == 1 && v instanceof String s) return kof_json_encode_string(s);
                    if (tag == 2) return kof_json_encode_bool(v instanceof Boolean b && b ? 1 : 0);
                    if (v instanceof Integer i) return kof_json_encode_int(i);
                    if (v instanceof Long l) return kof_json_encode_long(l);
                    return kof_json_encode(v);
                }

                private static String kof_json_encode_object(Object value) {
                    StringBuilder sb = new StringBuilder("{");
                    boolean first = true;
                    for (Field f : value.getClass().getDeclaredFields()) {
                        if (Modifier.isStatic(f.getModifiers())) continue;
                        try {
                            f.setAccessible(true);
                            Object v = f.get(value);
                            if (!first) sb.append(',');
                            first = false;
                            sb.append(kof_json_encode_string(f.getName()));
                            sb.append(':');
                            sb.append(kof_json_encode(v));
                        } catch (IllegalAccessException e) {
                            throw new RuntimeException("cannot encode field " + f.getName(), e);
                        }
                    }
                    sb.append('}');
                    return sb.toString();
                }

                public static int kof_json_decode_int(String json) {
                    return Integer.parseInt(json.trim());
                }

                public static long kof_json_decode_long(String json) {
                    return Long.parseLong(json.trim());
                }

                public static float kof_json_decode_float(String json) {
                    return Float.parseFloat(json.trim());
                }

                public static double kof_json_decode_double(String json) {
                    return Double.parseDouble(json.trim());
                }

                public static int kof_json_decode_bool(String json) {
                    return Boolean.parseBoolean(json.trim()) ? 1 : 0;
                }

                public static String kof_json_decode_string(String json) {
                    String s = json.trim();
                    int n = s.length();
                    if (n >= 2 && s.charAt(0) == '"' && s.charAt(n - 1) == '"')
                        return s.substring(1, n - 1);
                    return s;
                }

                public static int[] kof_json_decode_int_array(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof List<?> l) {
                        int n = l.size();
                        int[] out = new int[n];
                        for (int i = 0; i < n; i++) out[i] = ((Number) l.get(i)).intValue();
                        return out;
                    }
                    return new int[0];
                }

                public static long[] kof_json_decode_long_array(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof List<?> l) {
                        int n = l.size();
                        long[] out = new long[n];
                        for (int i = 0; i < n; i++) out[i] = ((Number) l.get(i)).longValue();
                        return out;
                    }
                    return new long[0];
                }

                // #132: Bool[] no JVM é boolean[] (JvmTypeMapper `Z`, new-array
                // T_BOOLEAN) — o decoder era o outlier que alojava int[], e só
                // "funcionava" porque o load usava IALOAD universal (ilegal num
                // boolean[] real). Representação única: BALOAD/BASTORE agora
                // batem em `new Bool[n]` E em `json.decode<Bool[]>`.
                public static boolean[] kof_json_decode_bool_array(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof List<?> l) {
                        int n = l.size();
                        boolean[] out = new boolean[n];
                        for (int i = 0; i < n; i++) out[i] = (Boolean) l.get(i);
                        return out;
                    }
                    return new boolean[0];
                }

                public static double[] kof_json_decode_double_array(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof List<?> l) {
                        int n = l.size();
                        double[] out = new double[n];
                        for (int i = 0; i < n; i++) out[i] = ((Number) l.get(i)).doubleValue();
                        return out;
                    }
                    return new double[0];
                }

                public static String[] kof_json_decode_string_array(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof List<?> l) {
                        int n = l.size();
                        String[] out = new String[n];
                        for (int i = 0; i < n; i++) out[i] = String.valueOf(l.get(i));
                        return out;
                    }
                    return new String[0];
                }

                public static ArrayList<Integer> kof_json_decode_int_list(String json) {
                    Object parsed = kof_json_parse(json);
                    ArrayList<Integer> result = new ArrayList<>();
                    if (parsed instanceof List<?> l)
                        for (Object e : l) result.add(((Number) e).intValue());
                    return result;
                }

                public static ArrayList<String> kof_json_decode_string_list(String json) {
                    Object parsed = kof_json_parse(json);
                    ArrayList<String> result = new ArrayList<>();
                    if (parsed instanceof List<?> l)
                        for (Object e : l) result.add(e == null ? null : String.valueOf(e));
                    return result;
                }

                public static ArrayList<Object> kof_json_decode_list(String json) {
                    Object parsed = kof_json_parse(json);
                    if (parsed instanceof ArrayList<?> l) return new ArrayList<Object>(l);
                    return new ArrayList<Object>();
                }

                public static ArrayList<Object> kof_json_decode_object_list(String json, String cn)
                        throws Exception {
                    Object parsed = kof_json_parse(json);
                    ArrayList<Object> result = new ArrayList<>();
                    if (parsed instanceof List<?> l) {
                        Class<?> type = Class.forName(cn);
                        for (Object e : l) result.add(kof_json_bind(type, e));
                    }
                    return result;
                }

                // §103.1 (#103): decode<Map<String,T>> — texto em
                // JvmRuntimeJsonMap (mesmo KofRuntime; split ≤500 byte-idêntico).
                // decode<Map<String,Classe>>: cada VALOR é bindado à classe
                // (idem — JvmRuntimeJsonMap).
                public static Object kof_json_decode_object(String json, Class<?> type) throws Exception {
                    return kof_json_bind(type, kof_json_parse(json));
                }

                private static Object kof_json_bind(Class<?> type, Object value) throws Exception {
                    return kof_json_bind(type, type, value);
                }

                // generic: o Type REFLETIDO do slot (RecordComponent.getGenericType /
                // Field.getGenericType) — preserva List<Addr> que o Class<?> apaga.
                // Sem isto, um campo List<Record> decodificava como lista de mapas
                // crus → ClassCastException no acesso (GitHub #34 / bug 58).
                private static Object kof_json_bind(Class<?> type, java.lang.reflect.Type generic, Object value) throws Exception {
                    if (value == null) return null;
                    if (type == String.class) return value instanceof String s ? s : String.valueOf(value);
                    // Numéricos: COERGE ao tipo do alvo (H2 `identity` → Long
                    // num record `Int` dava "argument type mismatch" na
                    // reflexão do record — read path do blog E2E F12).
                    if (type == int.class || type == Integer.class)
                        return value instanceof Number n ? n.intValue() : Integer.parseInt(String.valueOf(value));
                    if (type == long.class || type == Long.class)
                        return value instanceof Number n ? n.longValue() : Long.parseLong(String.valueOf(value));
                    if (type == byte.class || type == Byte.class)
                        return value instanceof Number n ? n.byteValue() : Byte.parseByte(String.valueOf(value));
                    if (type == short.class || type == Short.class)
                        return value instanceof Number n ? n.shortValue() : Short.parseShort(String.valueOf(value));
                    if (type == float.class || type == Float.class)
                        return value instanceof Number n ? n.floatValue() : Float.parseFloat(String.valueOf(value));
                    if (type == double.class || type == Double.class)
                        return value instanceof Number n ? n.doubleValue() : Double.parseDouble(String.valueOf(value));
                    if (type == Number.class) return value;
                    if (type == boolean.class || type == Boolean.class) {
                        if (value instanceof Boolean b) return b;
                        // §397: drivers SQL devolvem Integer p/ Bool no
                        // rs.getObject (SQLite int; H2) -- parseBoolean("1")
                        // virava false em SILENCIO em todo binder compartilhado
                        // (orm.find/all/where, db.query<T>, json.decode<T>).
                        // Numero !=0 -> true (regra do bind); string segue
                        // parseBoolean ("true"/"false" explicitos).
                        if (value instanceof Number n) return n.intValue() != 0;
                        return Boolean.parseBoolean(String.valueOf(value));
                    }
                    if (type == char.class || type == Character.class) {
                        return value.toString().charAt(0);
                    }
                    if (type.isAssignableFrom(ArrayList.class) || type == List.class || type == java.util.Collection.class) {
                        if (value instanceof List<?> l) {
                            java.lang.reflect.Type elem = listElement(generic);
                            if (elem == null) return new ArrayList<Object>(l);
                            ArrayList<Object> out = new ArrayList<>();
                            for (Object e : l) out.add(bindByType(elem, e));
                            return out;
                        }
                    }
                    if (value instanceof Map<?, ?> m) {
                        if (type.isRecord()) {
                            RecordComponent[] comps = type.getRecordComponents();
                            Class<?>[] argTypes = new Class<?>[comps.length];
                            Object[] args = new Object[comps.length];
                            for (int i = 0; i < comps.length; i++) {
                                argTypes[i] = comps[i].getType();
                                args[i] = kof_json_bind(comps[i].getType(), comps[i].getGenericType(), m.get(comps[i].getName()));
                            }
                            return type.getDeclaredConstructor(argTypes).newInstance(args);
                        }
                        Object obj = type.getDeclaredConstructor().newInstance();
                        for (Field f : type.getDeclaredFields()) {
                            if (Modifier.isStatic(f.getModifiers())) continue;
                            if (!m.containsKey(f.getName())) continue;
                            f.setAccessible(true);
                            Object v = kof_json_bind(f.getType(), f.getGenericType(), m.get(f.getName()));
                            if (v == null) continue;
                            if (f.getType() == int.class) f.setInt(obj, ((Number) v).intValue());
                            else if (f.getType() == long.class) f.setLong(obj, ((Number) v).longValue());
                            else if (f.getType() == short.class) f.setShort(obj, ((Number) v).shortValue());
                            else if (f.getType() == byte.class) f.setByte(obj, ((Number) v).byteValue());
                            else if (f.getType() == float.class) f.setFloat(obj, ((Number) v).floatValue());
                            else if (f.getType() == double.class) f.setDouble(obj, ((Number) v).doubleValue());
                            else if (f.getType() == boolean.class) f.setBoolean(obj, (Boolean) v);
                            else f.set(obj, v);
                        }
                        return obj;
                    }
                    return value;
                }

                // element type de um List<T>/Collection<T> refletido; null se não
                // parametrizado (lista crua) — o caller decide o fallback.
                private static java.lang.reflect.Type listElement(java.lang.reflect.Type generic) {
                    if (generic instanceof java.lang.reflect.ParameterizedType pt) {
                        java.lang.reflect.Type[] ta = pt.getActualTypeArguments();
                        if (ta.length == 1) return ta[0];
                    }
                    return null;
                }

                // binda um elemento de lista cujo tipo só é conhecido via reflexão
                // (Class, List<T> aninhado, ou Map<String,T>).
                private static Object bindByType(java.lang.reflect.Type elem, Object value) throws Exception {
                    if (value == null) return null;
                    if (elem instanceof Class<?> ec) return kof_json_bind(ec, ec, value);
                    if (elem instanceof java.lang.reflect.ParameterizedType pt)
                        return kof_json_bind((Class<?>) pt.getRawType(), pt, value);
                    return value;
                }

                public static Object kof_json_parse(String json) {
                    JsonParser p = new JsonParser(json);
                    Object v = p.parseValue();
                    p.skipWs();
                    if (p.pos < json.length()) throw new IllegalArgumentException("trailing JSON content at " + p.pos);
                    return v;
                }

                private static final class JsonParser {
                    private final String s;
                    private int pos;

                    JsonParser(String s) {
                        this.s = s;
                    }

                    void skipWs() {
                        while (pos < s.length() && Character.isWhitespace(s.charAt(pos))) pos++;
                    }

                    Object parseValue() {
                        skipWs();
                        if (pos >= s.length()) throw new IllegalArgumentException("unexpected end of JSON");
                        char c = s.charAt(pos);
                        if (c == '{') return parseObject();
                        if (c == '[') return parseArray();
                        if (c == '"') return parseString();
                        if (c == 't') { expect("true"); return Boolean.TRUE; }
                        if (c == 'f') { expect("false"); return Boolean.FALSE; }
                        if (c == 'n') { expect("null"); return null; }
                        if (c == '-' || (c >= '0' && c <= '9')) return parseNumber();
                        throw new IllegalArgumentException("unexpected JSON char '" + c + "' at " + pos);
                    }

                    private void expect(String word) {
                        if (!s.startsWith(word, pos)) throw new IllegalArgumentException("invalid JSON literal at " + pos);
                        pos += word.length();
                    }

                    private Map<String, Object> parseObject() {
                        Map<String, Object> map = new LinkedHashMap<>();
                        pos++;
                        skipWs();
                        if (pos < s.length() && s.charAt(pos) == '}') { pos++; return map; }
                        while (true) {
                            skipWs();
                            String key = parseString();
                            skipWs();
                            if (pos >= s.length() || s.charAt(pos) != ':') throw new IllegalArgumentException("expected ':' at " + pos);
                            pos++;
                            map.put(key, parseValue());
                            skipWs();
                            if (pos >= s.length()) throw new IllegalArgumentException("unterminated JSON object");
                            char c = s.charAt(pos);
                            if (c == ',') { pos++; continue; }
                            if (c == '}') { pos++; return map; }
                            throw new IllegalArgumentException("expected ',' or '}' at " + pos);
                        }
                    }

                    private List<Object> parseArray() {
                        List<Object> list = new ArrayList<>();
                        pos++;
                        skipWs();
                        if (pos < s.length() && s.charAt(pos) == ']') { pos++; return list; }
                        while (true) {
                            list.add(parseValue());
                            skipWs();
                            if (pos >= s.length()) throw new IllegalArgumentException("unterminated JSON array");
                            char c = s.charAt(pos);
                            if (c == ',') { pos++; continue; }
                            if (c == ']') { pos++; return list; }
                            throw new IllegalArgumentException("expected ',' or ']' at " + pos);
                        }
                    }

                    private String parseString() {
                        if (pos >= s.length() || s.charAt(pos) != '"') throw new IllegalArgumentException("expected string at " + pos);
                        pos++;
                        StringBuilder sb = new StringBuilder();
                        while (true) {
                            if (pos >= s.length()) throw new IllegalArgumentException("unterminated JSON string");
                            char c = s.charAt(pos);
                            if (c == '"') { pos++; return sb.toString(); }
                            if (c == '\\\\') {
                                pos++;
                                if (pos >= s.length()) throw new IllegalArgumentException("unterminated escape");
                                char e = s.charAt(pos);
                                switch (e) {
                                    case '"' -> sb.append('"');
                                    case '\\\\' -> sb.append('\\\\');
                                    case '/' -> sb.append('/');
                                    case 'n' -> sb.append('\\n');
                                    case 't' -> sb.append('\\t');
                                    case 'r' -> sb.append('\\r');
                                    case 'b' -> sb.append('\\b');
                                    case 'f' -> sb.append('\\f');
                                    case 'u' -> {
                                        if (pos + 4 >= s.length()) throw new IllegalArgumentException("bad \\\\u escape");
                                        sb.append((char) Integer.parseInt(s.substring(pos + 1, pos + 5), 16));
                                        pos += 4;
                                    }
                                    default -> throw new IllegalArgumentException("bad escape '\\\\" + e + "'");
                                }
                                pos++;
                            } else {
                                sb.append(c);
                                pos++;
                            }
                        }
                    }

                    private Object parseNumber() {
                        int start = pos;
                        if (pos < s.length() && s.charAt(pos) == '-') pos++;
                        while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                        boolean isDouble = false;
                        if (pos < s.length() && s.charAt(pos) == '.') {
                            isDouble = true;
                            pos++;
                            while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                        }
                        if (pos < s.length() && (s.charAt(pos) == 'e' || s.charAt(pos) == 'E')) {
                            isDouble = true;
                            pos++;
                            if (pos < s.length() && (s.charAt(pos) == '+' || s.charAt(pos) == '-')) pos++;
                            while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                        }
                        String num = s.substring(start, pos);
                        if (isDouble) return Double.parseDouble(num);
                        long l = Long.parseLong(num);
                        if (l >= Integer.MIN_VALUE && l <= Integer.MAX_VALUE) return (int) l;
                        return l;
                    }
                }

            %s
""".formatted(decoders);
    }
}
