package dev.kof.compiler.js;

/** kof-runtime.mjs — núcleo (helpers neutros de plataforma). */
public final class JsRuntimeCore {
    private JsRuntimeCore() {
    }

    // #104: o shim kof_platform abaixo é atribuído a globalThis (não `const`):
    // (1) o chunker do JsRuntimeSlices trata `const` no topo como início de
    // unit e arrastaria a fatia `globalThis.window` do préâmbulo para uma unit
    // prune-ável (sumia do artefato de quem não usa crypto); (2) o nome
    // "kof_platform" colidiria com o const do módulo io no mapa global de
    // providers (byte-identity do registry). Os blocos uuid/security/random/
    // crypto/ui-web citam o identificador cru, que resolve pela cadeia de
    // escopo até o global. Mensagem curta no .mjs para não inchar o hello.
    static  String CORE_RUNTIME = """
            // KofJS core runtime — platform-neutral helpers.
            // Generated by the Kof compiler (KofJS backend).
            // This module is not a VM: it only provides operations that
            // JavaScript does not represent directly.

            // #104: kof_platform só existe no host GraalJS; shim fora dele
            // (Node/browser) troca ReferenceError por erro claro (#104).
            if (!globalThis.kof_platform) {
                globalThis.kof_platform = new Proxy({
                    print(x) { console.log(String(x)); }
                }, {
                    get(t, prop) {
                        if (prop in t) return t[prop];
                        return function () {
                            throw new Error("kof_platform." + String(prop)
                                    + ": not available outside the Kof JS host");
                        };
                    }
                });
            }

            if (typeof document === "undefined") {
                function kofMakeEl(tag) {
                    const attrs = {};
                    const el = {
                        tagName: String(tag).toUpperCase(),
                        id: null,
                        className: "",
                        textContent: "",
                        value: "",
                        checked: false,
                        readOnly: false,
                        disabled: false,
                        selectedIndex: -1,
                        href: "",
                        target: "",
                        rel: "",
                        src: "",
                        alt: "",
                        width: 0,
                        height: 0,
                        type: "",
                        placeholder: "",
                        children: [],
                        parentNode: null,
                        style: {},
                        dataset: {},
                        _attrs: attrs,
                        classList: {
                            _set: new Set(),
                            add(cls) { this._set.add(cls); },
                            remove(cls) { this._set.delete(cls); },
                            toggle(cls) { if (this._set.has(cls)) { this._set.delete(cls); return false; } this._set.add(cls); return true; },
                            contains(cls) { return this._set.has(cls); }
                        },
                        setAttribute(name, value) {
                            attrs[String(name)] = String(value);
                            if (name === "id") el.id = String(value);
                            else if (name === "class") el.className = String(value);
                            else if (name === "width") el.width = parseInt(value, 10) || 0;
                            else if (name === "height") el.height = parseInt(value, 10) || 0;
                        },
                        getAttribute(name) {
                            if (name === "id") return el.id;
                            if (name === "class") return el.className;
                            if (name === "width") return el.width;
                            if (name === "height") return el.height;
                            return Object.prototype.hasOwnProperty.call(attrs, name) ? attrs[name] : null;
                        },
                        hasAttribute(name) { return el.getAttribute(name) !== null; },
                        removeAttribute(name) { delete attrs[name]; },
                        querySelector(sel) {
                            const want = String(sel).toUpperCase();
                            const stack = el.children.slice();
                            while (stack.length > 0) {
                                const n = stack.shift();
                                if (n.tagName === want) return n;
                                if (n.children) stack.push.apply(stack, n.children);
                            }
                            return null;
                        },
                        querySelectorAll(sel) {
                            const want = String(sel).toUpperCase();
                            const found = [];
                            const stack = el.children.slice();
                            while (stack.length > 0) {
                                const n = stack.shift();
                                if (n.tagName === want) found.push(n);
                                if (n.children) stack.push.apply(stack, n.children);
                            }
                            return found;
                        },
                        appendChild(child) {
                            if (child && child.parentNode) child.parentNode.removeChild(child);
                            child.parentNode = el;
                            el.children.push(child);
                            return child;
                        },
                        insertBefore(child, ref) {
                            if (child && child.parentNode) child.parentNode.removeChild(child);
                            child.parentNode = el;
                            const i = el.children.indexOf(ref);
                            if (i < 0) el.children.push(child);
                            else el.children.splice(i, 0, child);
                            return child;
                        },
                        removeChild(child) {
                            const i = el.children.indexOf(child);
                            if (i >= 0) { el.children.splice(i, 1); child.parentNode = null; }
                            return child;
                        },
                        remove() { if (el.parentNode) el.parentNode.removeChild(el); },
                        focus() {},
                        blur() {},
                        click() {
                            const hs = (el._handlers && el._handlers.click) || [];
                            for (const fn of hs) fn({ target: el, preventDefault() {}, stopPropagation() {} });
                        },
                        getContext(type) {
                            if (type !== "2d") return null;
                            return {
                                fillStyle: "#000", strokeStyle: "#000", lineWidth: 1,
                                globalAlpha: 1, font: "10px sans-serif",
                                textAlign: "left", textBaseline: "alphabetic",
                                beginPath() {}, closePath() {}, moveTo() {}, lineTo() {},
                                arc() {}, fill() {}, stroke() {}, clearRect() {},
                                fillRect() {}, strokeRect() {}, rect() {},
                                save() {}, restore() {}, translate() {}, rotate() {}, scale() {},
                                transform() {}, setTransform() {},
                                fillText() {}, strokeText() {},
                                measureText(text) { return { width: String(text).length * 6 }; },
                                drawImage() {},
                                createLinearGradient() { return { addColorStop() {} }; }
                            };
                        },
                        addEventListener(type, fn) { el._handlers = el._handlers || {}; (el._handlers[type] = el._handlers[type] || []).push(fn); },
                        removeEventListener(type, fn) {
                            const hs = el._handlers && el._handlers[type];
                            if (!hs) return;
                            const i = hs.indexOf(fn);
                            if (i >= 0) hs.splice(i, 1);
                        }
                    };
                    Object.defineProperty(el, "options", {
                        get() { return el.children.filter(function (c) { return c.tagName === "OPTION"; }); },
                        configurable: true
                    });
                    Object.defineProperty(el, "firstChild", {
                        get() { return el.children.length > 0 ? el.children[0] : null; },
                        configurable: true
                    });
                    Object.defineProperty(el, "innerHTML", {
                        get() { return ""; },
                        set(v) { if (v === "") { el.children.length = 0; } },
                        configurable: true
                    });
                    return el;
                }
                const kofRoot = kofMakeEl("div");
                kofRoot.id = "kof-root";
                const kofElements = { "kof-root": kofRoot };
                const kofHead = kofMakeEl("head");
                const kofHtml = kofMakeEl("html");
                kofHtml.appendChild(kofHead);
                globalThis.document = {
                    title: "",
                    head: kofHead,
                    body: kofRoot,
                    documentElement: kofHtml,
                    createElement(tag) { return kofMakeEl(tag); },
                    createElementNS(ns, tag) { return kofMakeEl(tag); },
                    createTextNode(text) { const t = kofMakeEl("#text"); t.textContent = String(text); return t; },
                    getElementById(id) { return kofElements[id] || null; },
                    querySelector(sel) { return kofRoot.querySelector(sel); },
                    querySelectorAll(sel) { return kofRoot.querySelectorAll(sel); }
                };
                globalThis.window = globalThis;
                globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
            }

            function kofEscapeHtml(s) {
                return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
                        .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
            }

            function kofSerialize(node) {
                if (!node) return "";
                const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
                let attrs = "";
                if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
                if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
                if (node.src) attrs += ' src="' + kofEscapeHtml(node.src) + '"';
                const kids = Array.from(node.children || []);
                const inner = kids.map(kofSerialize).join("");
                if (tag === "hr" || tag === "iframe" || tag === "br" || tag === "img") {
                    return "<" + tag + attrs + ">";
                }
                const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
                return "<" + tag + attrs + ">" + content + "</" + tag + ">";
            }

            export function kofUiSerializeHtml() {
                const root = document.getElementById("kof-root");
                if (!root) return "";
                const html = "<!DOCTYPE html>\\n<html>\\n<head>\\n<meta charset=\\"utf-8\\">\\n"
                        + "<meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1, viewport-fit=cover\\">\\n"
                        + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\\n"
                        + "</head>\\n<body>\\n" + kofSerialize(root) + "\\n</body>\\n</html>\\n";
                globalThis.kof__uiRootHtml = html;
                return html;
            }

            export function kofPrintln(x) {
                console.log(x);
            }

            // D-NULL-INTENT (#278): Boolean.valueOf(Z) no JS — normaliza
            // truthy/falsy num true/false estrito, mas PRESERVA null (Bool?
            // genuino de Map.get/put/remove agora carrega ausência real; o
            // ternário cru `x ? true : false` colapsava null -> false,
            // apagando a ausência no println/String.valueOf).
            export function kofBoolValueOf(x) {
                if (x === null || x === undefined) return null;
                return x ? true : false;
            }

            // #259: String.valueOf(Char?) — preserva "null" na ausência,
            // formata codepoint como caractere UTF-16 na presença.
            export function kofCharValueOf(x) {
                if (x === null || x === undefined) return "null";
                return typeof x === "number" ? String.fromCharCode(x) : String(x);
            }

            // §107-JS: formato de coleção idêntico ao contêiner JVM
            // (ArrayList/HashMap/HashSet.toString): elementos separados por
            // ", " dentro de [ ], Map como "{k=v}". Elementos passam por
            // valueOf de novo (String → toString/record). Não toca no
            // path de valor primitivo escalar (bug 44 / String(x)).
            // §111: split com a regra Java (não JS): remove vazios TRAILING,
            // exceto input "" → [""]. JS nativo preserva trailing ("a,"→["a",""]).
            export function kofSplit(s, sep) {
                const parts = String(s).split(sep === undefined ? "" : sep);
                if (s === "") return [""];
                let end = parts.length;
                while (end > 0 && parts[end - 1] === "") end--;
                return parts.slice(0, end);
            }

            export function kofFormat(x) {
                if (x instanceof Map) {
                    let s = "{";
                    let first = true;
                    for (const [k, v] of x) {
                        if (!first) s += ", ";
                        first = false;
                        s += kofElem(k) + "=" + kofElem(v);
                    }
                    return s + "}";
                }
                if (x instanceof Set) {
                    let parts = [];
                    for (const e of x) parts.push(kofElem(e));
                    return "[" + parts.join(", ") + "]";
                }
                if (Array.isArray(x)) {
                    const parts = x.map(kofElem);
                    return "[" + parts.join(", ") + "]";
                }
                return String(x);
            }
            function kofElem(v) {
                if (v === null || v === undefined) return "null";
                if (Array.isArray(v)) return kofFormat(v);
                if (v instanceof Map || v instanceof Set) return kofFormat(v);
                if (typeof v === "object" && typeof v.toString === "function") {
                    // §104c: record/objeto Kof sempre ganha toString() sintético
                    // ("Point[x=1, y=2]", JsClassEmitter.lowerRecordToString).
                    // Nunca cai em JSON.stringify (que dava o `[object Object]`
                    // disfarçado). Escalares seguem String(x).
                    return v.toString();
                }
                return String(v);
            }

            // Array multidimensional (bug 71): new T[d1][d2]...[dn].
            // sizes = dims externas→internas; baseFill preenche a folha.
            // JVM: MULTIANEWARRAY cria dims-1 preenchidas com arrays vazios
            // (não preenche recursivamente) — mesmo comportamento aqui.
            export function kofMultiArray(sizes, dims, baseFill) {
                if (dims === 1) {
                    return new Array(sizes[0]).fill(baseFill);
                }
                const outer = new Array(sizes[0]);
                for (let i = 0; i < sizes[0]; i++) {
                    outer[i] = kofMultiArray(sizes.slice(1), dims - 1, baseFill);
                }
                return outer;
            }

            // KOF-SBD-001 — Array Bounds Safety: JVM aaload/aastore/iaload/...
            // already bounds-check per the JVM spec (§6.5); raw JS `array[i]`
            // does not (out-of-bounds read → undefined, out-of-bounds write →
            // silent grow). These helpers close that KofJS-only gap so an
            // invalid Kof array access is rejected the same way on every
            // target, without claiming Kof is memory-safe as a whole.
            export function kofArrayGet(array, index) {
                if (index < 0 || index >= array.length) {
                    throw new Error("Array index out of bounds: " + index + " (length " + array.length + ")");
                }
                return array[index];
            }

            export function kofArraySet(array, index, value, kind) {
                if (index < 0 || index >= array.length) {
                    throw new Error("Array index out of bounds: " + index + " (length " + array.length + ")");
                }
                // §184/§187: narrow to the element width on write, like the
                // JVM (i2b/i2s/i2c), Native (mask) and Script targets.
                // kind: 1 = byte (i2b), 2 = short (i2s), 3 = char (i2c), 0 = none.
                if (kind === 1) {
                    array[index] = (value << 24) >> 24;
                } else if (kind === 2) {
                    array[index] = (value << 16) >> 16;
                } else if (kind === 3) {
                    array[index] = value & 0xFFFF;
                } else {
                    array[index] = value;
                }
            }

            // hashCode de valor Kof: espelha o Objects.hashCode/record JVM.
            // primitivos numéricos → int32 (wrap), String → algoritmo Java,
            // record → hashCode() sintético, senão → hash de String(valor).
            export function kofHashCode(v) {
                if (v === null || v === undefined) return 0;
                const t = typeof v;
                if (t === "number") return v | 0;
                if (t === "string") {
                    let h = 0;
                    for (let i = 0; i < v.length; i++) h = (31 * h + v.charCodeAt(i)) | 0;
                    return h;
                }
                if (t === "boolean") return v ? 1 : 0;
                if (typeof v.hashCode === "function") return v.hashCode();
                return kofHashCode(String(v));
            }

            // String.compareTo: espelha o JVM (bug 97, face JS) — walk de
            // code units UTF-16: primeira unit diferente → A−B; prefixo →
            // diferença de contagem de units (charCodeAt = UTF-16 unit, como
            // no asm x86 .Lct_diff — NAO String.localeCompare, que diverge
            // de locale e de astral).
            export function kofStringCompareTo(a, b) {
                const la = a.length, lb = b.length;
                const n = la < lb ? la : lb;
                for (let i = 0; i < n; i++) {
                    const u = a.charCodeAt(i), v = b.charCodeAt(i);
                    if (u !== v) return u - v;
                }
                return la - lb;
            }

            // String.compareToIgnoreCase: espelha o JVM (CASE_INSENSITIVE_ORDER)
            // — walk de code units UTF-16 com fold SIMPLES por unit: upper,
            // senão lower; prefixo -> contagem de units A−B. O "fold simples"
            // evita as expansões que o JVM NAO usa aqui (ex.: "ß".toUpperCase()
            // = "SS" no JS, mas Character.toUpperCase('ß')='ß' no JVM): se o
            // built-in devolve mais de 1 unidade, mantem a unit original.
            function kofSimpleUpper(c) {
                const s = String.fromCharCode(c).toUpperCase();
                return s.length === 1 ? s.charCodeAt(0) : c;
            }
            function kofSimpleLower(c) {
                if (c === 0x0130) return 0x0069; // İ: lower SIMPLES = i (JVM)
                const s = String.fromCharCode(c).toLowerCase();
                return s.length === 1 ? s.charCodeAt(0) : c;
            }
            export function kofStringCompareToIgnoreCase(a, b) {
                const la = a.length, lb = b.length;
                const n = la < lb ? la : lb;
                for (let i = 0; i < n; i++) {
                    const c1 = a.charCodeAt(i), c2 = b.charCodeAt(i);
                    if (c1 === c2) continue;
                    const u1 = kofSimpleUpper(c1), u2 = kofSimpleUpper(c2);
                    if (u1 !== u2) {
                        const l1 = kofSimpleLower(u1), l2 = kofSimpleLower(u2);
                        if (l1 !== l2) return l1 - l2;
                    }
                }
                return la - lb;
            }

            // String.toCharArray: espelha o JVM — array de code units UTF-16
            // (charCodeAt por índice; array de números = Char[] no JS). NAO
            // Array.from(s)/spread, que separa por code POINT e fundiria o par
            // astral num elemento (o JVM devolve 2 elementos por par astral).
            export function kofToCharArray(s) {
                const n = s.length;
                const a = new Array(n);
                for (let i = 0; i < n; i++) a[i] = s.charCodeAt(i);
                return a;
            }

            let kofLogLevel = 1; // default "info": 0 debug, 1 info, 2 warn, 3 error, 4 off
            try {
                const lv = (process.env.KOF_LOG_LEVEL || "info").trim().toLowerCase();
                if (lv === "debug") kofLogLevel = 0;
                else if (lv === "warn") kofLogLevel = 2;
                else if (lv === "error") kofLogLevel = 3;
                else if (lv === "off") kofLogLevel = 4;
            } catch (e) { /* non-node env: keep default */ }

            export function kofLogDebug(msg) { if (kofLogLevel <= 0) console.log(String(msg)); }
            export function kofLogInfo(msg)  { if (kofLogLevel <= 1) console.log(String(msg)); }
            export function kofLogWarn(msg)  { if (kofLogLevel <= 2) (console.warn || console.log)(String(msg)); }
            export function kofLogError(msg) { if (kofLogLevel <= 3) (console.error || console.log)(String(msg)); }

            export function kofUiWindowNew(title) {
                if (typeof document === "undefined") {
                    return -1;
                }
                kofUiInjectTheme();
                const root = document.getElementById("kof-root");
                if (!root) {
                    return -1;
                }
                if (typeof window.__kofWindows === "undefined") {
                    window.__kofWindows = {};
                }
                const id = Object.keys(window.__kofWindows).length + 1;
                const winEl = document.createElement("div");
                winEl.className = "kof-window";
                window.__kofWindows[id] = winEl;
                document.title = title;
                root.appendChild(winEl);
                return id;
            }

            // Kof UI theme — the same Dracula/VSCode aesthetic in every host
            // (browser, webview, KofWebHost): one Kof program, one look.
            function kofUiInjectTheme() {
                if (typeof document === "undefined") return;
                if (document.getElementById("kof-theme")) return;
                const style = document.createElement("style");
                style.id = "kof-theme";
                style.textContent = [
                    ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
                    "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
                    "html, body { margin:0; height:100%; overflow:hidden; }",
                    "body { background:var(--bg); color:var(--fg); font-family:",
                    '  "Cascadia Code", "Fira Code", Consolas, Menlo, monospace; }',
                    ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
                    "  white-space:pre-wrap; padding:2px 0; }",
                    // issues #75/#76 (10/09): o runtime AO VIVO não tinha NENHUMA
                    // regra p/ Column/Row (renderizavam divs crus, sem flex) nem
                    // p/ Button/Input/Textarea/Select (controles nativos crus).
                    // Espelha o exportador ESTÁTICO (JsArtifactWriter) no MESMO
                    // vocabulário de var(--…) do tema — paridade vivo↔estático.
                    ".kof-column { display:flex; flex-direction:column; gap:8px; }",
                    ".kof-row { display:flex; flex-direction:row; flex-wrap:wrap;",
                    "  gap:8px; align-items:flex-start; }",
                    ".kof-button { font-size:13px; padding:6px 14px; cursor:pointer;",
                    "  background:var(--panel); color:var(--fg);",
                    "  border:1px solid var(--border); border-radius:6px; }",
                    ".kof-button:hover { background:var(--hover); }",
                    ".kof-input, .kof-textarea, .kof-select { font-size:13px; padding:6px 10px;",
                    "  background:var(--panel); color:var(--fg); font-family:inherit;",
                    "  border:1px solid var(--border); border-radius:6px; }",
                    ".kof-input { width:100%; }",
                    ".kof-view { box-sizing:border-box; }",
                    ".kof-window { box-sizing:border-box; padding:16px; border-radius:8px;",
                    "  border:1px solid var(--border); background:var(--bg);",
                    "  display:flex; flex-direction:column; gap:8px; }"
                ].join("\\n");
                (document.head || document.documentElement).appendChild(style);
            }

            export function kofUiWindowSetTitle(window, title) {
                if (typeof document !== "undefined") {
                    document.title = title;
                }
            }

            export function kofUiWindowTitle(window) {
                return typeof document !== "undefined" ? document.title : "";
            }

            export function kofUiWindowBind(win, label) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (!winEl) return;
                // Component Core: a component binds under the window and mounts
                // (view + onMount) — lifecycle is automatic.
                const comp = kofUiComponents.get(label);
                if (comp) {
                    if (comp.el) winEl.appendChild(comp.el);
                    kofUiComponentMount(label);
                    return;
                }
                const nodes = globalThis.window && globalThis.window.__kofNodes;
                const node = nodes && nodes[label];
                if (node) {
                    winEl.appendChild(node);
                }
            }

            export function kofUiWindowShow(window) {
                kofUiSerializeHtml();
            }

            export function kofUiWindowSetSize(win, width, height) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (winEl) {
                    winEl.style.width = width + "px";
                    winEl.style.height = height + "px";
                }
                try {
                    if (typeof globalThis.window !== "undefined"
                            && typeof globalThis.window.resizeTo === "function") {
                        globalThis.window.resizeTo(width, height);
                    }
                } catch (e) {
                    // resizeTo is blocked on some hosts; the CSS sizing above
                    // still constrains the window content.
                }
            }

            export function kofUiWindowClose(win) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (winEl) {
                    if (winEl.parentNode) {
                        winEl.parentNode.removeChild(winEl);
                    }
                    delete globalThis.window.__kofWindows[win];
                }
            }

            export function kofUiWindowSetTheme(window, theme) {
                if (typeof document === "undefined") {
                    return;
                }
                const root = document.getElementById("kof-root");
                if (!root) {
                    return;
                }
                const colors = theme
                        ? { background: 0x121212FF, text: 0xFFFFFFFF }
                        : { background: 0xFFFFFFFF, text: 0x000000FF };
                root.style.backgroundColor = kofUiColorToCss(colors.background);
                root.style.color = kofUiColorToCss(colors.text);
            }
            """;

}
