package dev.kof.compiler.js;

/** kof-runtime.mjs — núcleo (helpers neutros de plataforma). */
public final class JsRuntimeCore {
    private JsRuntimeCore() {
    }

    static final String CORE_RUNTIME = """
            // KofJS core runtime — platform-neutral helpers.
            // Generated by the Kof compiler (KofJS backend).
            // This module is not a VM: it only provides operations that
            // JavaScript does not represent directly.

            if (typeof document === "undefined") {
                function kofMakeEl(tag) {
                    return {
                        tagName: String(tag).toUpperCase(),
                        id: null,
                        className: "",
                        textContent: "",
                        children: [],
                        parentNode: null,
                        style: {},
                        appendChild(child) {
                            if (child && child.parentNode) child.parentNode.removeChild(child);
                            child.parentNode = this;
                            this.children.push(child);
                            return child;
                        },
                        removeChild(child) {
                            const i = this.children.indexOf(child);
                            if (i >= 0) { this.children.splice(i, 1); child.parentNode = null; }
                            return child;
                        },
                        remove() { if (this.parentNode) this.parentNode.removeChild(this); },
                        getContext(type) {
                            if (type !== "2d") return null;
                            return {
                                fillStyle: "#000", strokeStyle: "#000", lineWidth: 1,
                                beginPath() {}, closePath() {}, moveTo() {}, lineTo() {},
                                arc() {}, fill() {}, stroke() {}, clearRect() {}
                            };
                        },
                        addEventListener(type, fn) { this._handlers = this._handlers || {}; (this._handlers[type] = this._handlers[type] || []).push(fn); }
                    };
                }
                const kofRoot = kofMakeEl("div");
                kofRoot.id = "kof-root";
                const kofElements = { "kof-root": kofRoot };
                const kofHead = kofMakeEl("head");
                const kofHtml = kofMakeEl("html");
                kofHtml.appendChild(kofHead);
                globalThis.document = {
                    title: "",
                    head: kofHead,
                    documentElement: kofHtml,
                    createElement(tag) { return kofMakeEl(tag); },
                    getElementById(id) { return kofElements[id] || null; }
                };
                globalThis.window = globalThis;
                globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
            }

            function kofEscapeHtml(s) {
                return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
                        .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
            }

            function kofSerialize(node) {
                if (!node) return "";
                const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
                let attrs = "";
                if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
                if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
                if (node.src) attrs += ' src="' + kofEscapeHtml(node.src) + '"';
                const kids = Array.from(node.children || []);
                const inner = kids.map(kofSerialize).join("");
                if (tag === "hr" || tag === "iframe" || tag === "br" || tag === "img") {
                    return "<" + tag + attrs + ">";
                }
                const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
                return "<" + tag + attrs + ">" + content + "</" + tag + ">";
            }

            export function kofUiSerializeHtml() {
                const root = document.getElementById("kof-root");
                if (!root) return "";
                const html = "<!DOCTYPE html>\\n<html>\\n<head>\\n<meta charset=\\"utf-8\\">\\n"
                        + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\\n"
                        + "</head>\\n<body>\\n" + kofSerialize(root) + "\\n</body>\\n</html>\\n";
                globalThis.kof__uiRootHtml = html;
                return html;
            }

            export function kofPrintln(x) {
                console.log(x);
            }

            // §107-JS: formato de coleção idêntico ao contêiner JVM
            // (ArrayList/HashMap/HashSet.toString): elementos separados por
            // ", " dentro de [ ], Map como "{k=v}". Elementos passam por
            // valueOf de novo (String → toString/record). Não toca no
            // path de valor primitivo escalar (bug 44 / String(x)).
            // §104c: igualdade de conteúdo em coleções JS. Primitivos/String
            // resolvem no caminho nativo (SameValueZero) — o fallback só pega
            // objeto Kof (record) que traz .equals(other) sintético → 1/0.
            // Assim `listOf(p1).contains(p2)`, `setOf/mapOf` por conteúdo batem
            // com o oracle JVM sem alterar o armazenamento nem o kofFormat.
            function kofValEq(a, b) {
                if (a === b) return true;
                if (Number.isNaN(a) && Number.isNaN(b)) return true;
                if (a === null || b === null || a === undefined || b === undefined) return false;
                if (typeof a === "object" && typeof a.equals === "function") {
                    return a.equals(b) ? true : false;
                }
                return false;
            }

            // §111: split com a regra Java (não JS): remove vazios TRAILING,
            // exceto input "" → [""]. JS nativo preserva trailing ("a,"→["a",""]).
            export function kofSplit(s, sep) {
                const parts = String(s).split(sep === undefined ? "" : sep);
                if (s === "") return [""];
                let end = parts.length;
                while (end > 0 && parts[end - 1] === "") end--;
                return parts.slice(0, end);
            }

            export function kofFormat(x) {
                if (x instanceof Map) {
                    let s = "{";
                    let first = true;
                    for (const [k, v] of x) {
                        if (!first) s += ", ";
                        first = false;
                        s += kofElem(k) + "=" + kofElem(v);
                    }
                    return s + "}";
                }
                if (x instanceof Set) {
                    let parts = [];
                    for (const e of x) parts.push(kofElem(e));
                    return "[" + parts.join(", ") + "]";
                }
                if (Array.isArray(x)) {
                    const parts = x.map(kofElem);
                    return "[" + parts.join(", ") + "]";
                }
                return String(x);
            }
            function kofElem(v) {
                if (v === null || v === undefined) return "null";
                if (Array.isArray(v)) return kofFormat(v);
                if (v instanceof Map || v instanceof Set) return kofFormat(v);
                if (typeof v === "object" && typeof v.toString === "function") {
                    // §104c: record/objeto Kof sempre ganha toString() sintético
                    // ("Point[x=1, y=2]", JsClassEmitter.lowerRecordToString).
                    // Nunca cai em JSON.stringify (que dava o `[object Object]`
                    // disfarçado). Escalares seguem String(x).
                    return v.toString();
                }
                return String(v);
            }

            // Array multidimensional (bug 71): new T[d1][d2]...[dn].
            // sizes = dims externas→internas; baseFill preenche a folha.
            // JVM: MULTIANEWARRAY cria dims-1 preenchidas com arrays vazios
            // (não preenche recursivamente) — mesmo comportamento aqui.
            export function kofMultiArray(sizes, dims, baseFill) {
                if (dims === 1) {
                    return new Array(sizes[0]).fill(baseFill);
                }
                const outer = new Array(sizes[0]);
                for (let i = 0; i < sizes[0]; i++) {
                    outer[i] = kofMultiArray(sizes.slice(1), dims - 1, baseFill);
                }
                return outer;
            }

            // hashCode de valor Kof: espelha o Objects.hashCode/record JVM.
            // primitivos numéricos → int32 (wrap), String → algoritmo Java,
            // record → hashCode() sintético, senão → hash de String(valor).
            export function kofHashCode(v) {
                if (v === null || v === undefined) return 0;
                const t = typeof v;
                if (t === "number") return v | 0;
                if (t === "string") {
                    let h = 0;
                    for (let i = 0; i < v.length; i++) h = (31 * h + v.charCodeAt(i)) | 0;
                    return h;
                }
                if (t === "boolean") return v ? 1 : 0;
                if (typeof v.hashCode === "function") return v.hashCode();
                return kofHashCode(String(v));
            }

            // String.compareTo: espelha o JVM (bug 97, face JS) — walk de
            // code units UTF-16: primeira unit diferente → A−B; prefixo →
            // diferença de contagem de units (charCodeAt = UTF-16 unit, como
            // no asm x86 .Lct_diff — NAO String.localeCompare, que diverge
            // de locale e de astral).
            export function kofStringCompareTo(a, b) {
                const la = a.length, lb = b.length;
                const n = la < lb ? la : lb;
                for (let i = 0; i < n; i++) {
                    const u = a.charCodeAt(i), v = b.charCodeAt(i);
                    if (u !== v) return u - v;
                }
                return la - lb;
            }

            let kofLogLevel = 1; // default "info": 0 debug, 1 info, 2 warn, 3 error, 4 off
            try {
                const lv = (process.env.KOF_LOG_LEVEL || "info").trim().toLowerCase();
                if (lv === "debug") kofLogLevel = 0;
                else if (lv === "warn") kofLogLevel = 2;
                else if (lv === "error") kofLogLevel = 3;
                else if (lv === "off") kofLogLevel = 4;
            } catch (e) { /* non-node env: keep default */ }

            export function kofLogDebug(msg) { if (kofLogLevel <= 0) console.log(String(msg)); }
            export function kofLogInfo(msg)  { if (kofLogLevel <= 1) console.log(String(msg)); }
            export function kofLogWarn(msg)  { if (kofLogLevel <= 2) (console.warn || console.log)(String(msg)); }
            export function kofLogError(msg) { if (kofLogLevel <= 3) (console.error || console.log)(String(msg)); }

            export function kofUiWindowNew(title) {
                if (typeof document === "undefined") {
                    return -1;
                }
                kofUiInjectTheme();
                const root = document.getElementById("kof-root");
                if (!root) {
                    return -1;
                }
                if (typeof window.__kofWindows === "undefined") {
                    window.__kofWindows = {};
                }
                const id = Object.keys(window.__kofWindows).length + 1;
                const winEl = document.createElement("div");
                winEl.className = "kof-window";
                window.__kofWindows[id] = winEl;
                document.title = title;
                root.appendChild(winEl);
                return id;
            }

            // Kof UI theme — the same Dracula/VSCode aesthetic in every host
            // (browser, webview, KofWebHost): one Kof program, one look.
            function kofUiInjectTheme() {
                if (typeof document === "undefined") return;
                if (document.getElementById("kof-theme")) return;
                const style = document.createElement("style");
                style.id = "kof-theme";
                style.textContent = [
                    ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
                    "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
                    "html, body { margin:0; height:100%; overflow:hidden; }",
                    "body { background:var(--bg); color:var(--fg); font-family:",
                    '  "Cascadia Code", "Fira Code", Consolas, Menlo, monospace; }',
                    ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
                    "  white-space:pre-wrap; padding:2px 0; }",
                    // issues #75/#76 (10/09): o runtime AO VIVO não tinha NENHUMA
                    // regra p/ Column/Row (renderizavam divs crus, sem flex) nem
                    // p/ Button/Input/Textarea/Select (controles nativos crus).
                    // Espelha o exportador ESTÁTICO (JsArtifactWriter) no MESMO
                    // vocabulário de var(--…) do tema — paridade vivo↔estático.
                    ".kof-column { display:flex; flex-direction:column; gap:8px; }",
                    ".kof-row { display:flex; flex-direction:row; flex-wrap:wrap;",
                    "  gap:8px; align-items:flex-start; }",
                    ".kof-button { font-size:13px; padding:6px 14px; cursor:pointer;",
                    "  background:var(--panel); color:var(--fg);",
                    "  border:1px solid var(--border); border-radius:6px; }",
                    ".kof-button:hover { background:var(--hover); }",
                    ".kof-input, .kof-textarea, .kof-select { font-size:13px; padding:6px 10px;",
                    "  background:var(--panel); color:var(--fg); font-family:inherit;",
                    "  border:1px solid var(--border); border-radius:6px; }",
                    ".kof-input { width:100%; }",
                    ".kof-view { box-sizing:border-box; }",
                    ".kof-window { box-sizing:border-box; padding:16px; border-radius:8px;",
                    "  border:1px solid var(--border); background:var(--bg);",
                    "  display:flex; flex-direction:column; gap:8px; }"
                ].join("\\n");
                (document.head || document.documentElement).appendChild(style);
            }

            export function kofUiWindowSetTitle(window, title) {
                if (typeof document !== "undefined") {
                    document.title = title;
                }
            }

            export function kofUiWindowTitle(window) {
                return typeof document !== "undefined" ? document.title : "";
            }

            export function kofUiWindowBind(win, label) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (!winEl) return;
                // Component Core: a component binds under the window and mounts
                // (view + onMount) — lifecycle is automatic.
                const comp = kofUiComponents.get(label);
                if (comp) {
                    if (comp.el) winEl.appendChild(comp.el);
                    kofUiComponentMount(label);
                    return;
                }
                const nodes = globalThis.window && globalThis.window.__kofNodes;
                const node = nodes && nodes[label];
                if (node) {
                    winEl.appendChild(node);
                }
            }

            export function kofUiWindowShow(window) {
                kofUiSerializeHtml();
            }

            export function kofUiWindowSetSize(window, width, height) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    winEl.style.width = width + "px";
                    winEl.style.height = height + "px";
                }
                try {
                    if (typeof window.resizeTo === "function") {
                        window.resizeTo(width, height);
                    }
                } catch (e) {
                    // resizeTo is blocked on some hosts; the CSS sizing above
                    // still constrains the window content.
                }
            }

            export function kofUiWindowClose(window) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    if (winEl.parentNode) {
                        winEl.parentNode.removeChild(winEl);
                    }
                    delete window.__kofWindows[window];
                }
            }

            export function kofUiWindowSetTheme(window, theme) {
                if (typeof document === "undefined") {
                    return;
                }
                const root = document.getElementById("kof-root");
                if (!root) {
                    return;
                }
                const colors = theme
                        ? { background: 0x121212FF, text: 0xFFFFFFFF }
                        : { background: 0xFFFFFFFF, text: 0x000000FF };
                root.style.backgroundColor = kofUiColorToCss(colors.background);
                root.style.color = kofUiColorToCss(colors.text);
            }
            """;

}
