package dev.kof.compiler.js;

/** kof-runtime.mjs — núcleo (helpers neutros de plataforma). */
public final class JsRuntimeCore {
    private JsRuntimeCore() {
    }

    static final String CORE_RUNTIME = """
            // KofJS core runtime — platform-neutral helpers.
            // Generated by the Kof compiler (KofJS backend).
            // This module is not a VM: it only provides operations that
            // JavaScript does not represent directly.

            if (typeof document === "undefined") {
                function kofMakeEl(tag) {
                    return {
                        tagName: String(tag).toUpperCase(),
                        id: null,
                        className: "",
                        textContent: "",
                        children: [],
                        parentNode: null,
                        style: {},
                        appendChild(child) {
                            if (child && child.parentNode) child.parentNode.removeChild(child);
                            child.parentNode = this;
                            this.children.push(child);
                            return child;
                        },
                        removeChild(child) {
                            const i = this.children.indexOf(child);
                            if (i >= 0) { this.children.splice(i, 1); child.parentNode = null; }
                            return child;
                        },
                        remove() { if (this.parentNode) this.parentNode.removeChild(this); },
                        getContext(type) {
                            if (type !== "2d") return null;
                            return {
                                fillStyle: "#000", strokeStyle: "#000", lineWidth: 1,
                                beginPath() {}, closePath() {}, moveTo() {}, lineTo() {},
                                arc() {}, fill() {}, stroke() {}, clearRect() {}
                            };
                        },
                        addEventListener(type, fn) { this._handlers = this._handlers || {}; (this._handlers[type] = this._handlers[type] || []).push(fn); }
                    };
                }
                const kofRoot = kofMakeEl("div");
                kofRoot.id = "kof-root";
                const kofElements = { "kof-root": kofRoot };
                const kofHead = kofMakeEl("head");
                const kofHtml = kofMakeEl("html");
                kofHtml.appendChild(kofHead);
                globalThis.document = {
                    title: "",
                    head: kofHead,
                    documentElement: kofHtml,
                    createElement(tag) { return kofMakeEl(tag); },
                    getElementById(id) { return kofElements[id] || null; }
                };
                globalThis.window = globalThis;
                globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
            }

            function kofEscapeHtml(s) {
                return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
                        .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
            }

            function kofSerialize(node) {
                if (!node) return "";
                const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
                let attrs = "";
                if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
                if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
                if (node.src) attrs += ' src="' + kofEscapeHtml(node.src) + '"';
                const kids = Array.from(node.children || []);
                const inner = kids.map(kofSerialize).join("");
                if (tag === "hr" || tag === "iframe" || tag === "br" || tag === "img") {
                    return "<" + tag + attrs + ">";
                }
                const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
                return "<" + tag + attrs + ">" + content + "</" + tag + ">";
            }

            export function kofUiSerializeHtml() {
                const root = document.getElementById("kof-root");
                if (!root) return "";
                const html = "<!DOCTYPE html>\\n<html>\\n<head>\\n<meta charset=\\"utf-8\\">\\n"
                        + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\\n"
                        + "</head>\\n<body>\\n" + kofSerialize(root) + "\\n</body>\\n</html>\\n";
                globalThis.kof__uiRootHtml = html;
                return html;
            }

            export function kofPrintln(x) {
                console.log(x);
            }

            // Array multidimensional (bug 71): new T[d1][d2]...[dn].
            // sizes = dims externas→internas; baseFill preenche a folha.
            // JVM: MULTIANEWARRAY cria dims-1 preenchidas com arrays vazios
            // (não preenche recursivamente) — mesmo comportamento aqui.
            export function kofMultiArray(sizes, dims, baseFill) {
                if (dims === 1) {
                    return new Array(sizes[0]).fill(baseFill);
                }
                const outer = new Array(sizes[0]);
                for (let i = 0; i < sizes[0]; i++) {
                    outer[i] = kofMultiArray(sizes.slice(1), dims - 1, baseFill);
                }
                return outer;
            }

            // hashCode de valor Kof: espelha o Objects.hashCode/record JVM.
            // primitivos numéricos → int32 (wrap), String → algoritmo Java,
            // record → hashCode() sintético, senão → hash de String(valor).
            export function kofHashCode(v) {
                if (v === null || v === undefined) return 0;
                const t = typeof v;
                if (t === "number") return v | 0;
                if (t === "string") {
                    let h = 0;
                    for (let i = 0; i < v.length; i++) h = (31 * h + v.charCodeAt(i)) | 0;
                    return h;
                }
                if (t === "boolean") return v ? 1 : 0;
                if (typeof v.hashCode === "function") return v.hashCode();
                return kofHashCode(String(v));
            }

            let kofLogLevel = 1; // default "info": 0 debug, 1 info, 2 warn, 3 error, 4 off
            try {
                const lv = (process.env.KOF_LOG_LEVEL || "info").trim().toLowerCase();
                if (lv === "debug") kofLogLevel = 0;
                else if (lv === "warn") kofLogLevel = 2;
                else if (lv === "error") kofLogLevel = 3;
                else if (lv === "off") kofLogLevel = 4;
            } catch (e) { /* non-node env: keep default */ }

            export function kofLogDebug(msg) { if (kofLogLevel <= 0) console.log(String(msg)); }
            export function kofLogInfo(msg)  { if (kofLogLevel <= 1) console.log(String(msg)); }
            export function kofLogWarn(msg)  { if (kofLogLevel <= 2) (console.warn || console.log)(String(msg)); }
            export function kofLogError(msg) { if (kofLogLevel <= 3) (console.error || console.log)(String(msg)); }

            export function kofUiWindowNew(title) {
                if (typeof document === "undefined") {
                    return -1;
                }
                kofUiInjectTheme();
                const root = document.getElementById("kof-root");
                if (!root) {
                    return -1;
                }
                if (typeof window.__kofWindows === "undefined") {
                    window.__kofWindows = {};
                }
                const id = Object.keys(window.__kofWindows).length + 1;
                const winEl = document.createElement("div");
                winEl.className = "kof-window";
                window.__kofWindows[id] = winEl;
                document.title = title;
                root.appendChild(winEl);
                return id;
            }

            // Kof UI theme — the same Dracula/VSCode aesthetic in every host
            // (browser, webview, KofWebHost): one Kof program, one look.
            function kofUiInjectTheme() {
                if (typeof document === "undefined") return;
                if (document.getElementById("kof-theme")) return;
                const style = document.createElement("style");
                style.id = "kof-theme";
                style.textContent = [
                    ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
                    "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
                    "html, body { margin:0; height:100%; overflow:hidden; }",
                    // UI font stack (docs/ui/architecture.md design-system gap:
                    // "não há tokens de Typography"). Widget.setFont() throws
                    // before the window opens in kof run's headless-DOM
                    // detection pass (n.dataset write on a DOM without
                    // `dataset`), so this is set once here instead — a sans
                    // stack fits a general UI window better than the previous
                    // fixed monospace default, which stays available per
                    // element via an explicit font-family if ever needed.
                    "body { background:var(--bg); color:var(--fg); font-family:",
                    "  -apple-system, \\"Segoe UI\\", Roboto, Inter, Arial, sans-serif; }",
                    ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
                    "  white-space:pre-wrap; padding:2px 0; }",
                    // Column/Row are documented as flexbox (docs/ui/architecture.md
                    // §1: "CSS flexbox; gap fixo 8px") but had no matching rule on
                    // this (live) runtime path — only the static artifact export
                    // defined it. Restored here, with wrap on Row so multi-card
                    // rows collapse to one column on narrow viewports without any
                    // media query.
                    ".kof-column { display:flex; flex-direction:column; gap:8px; }",
                    ".kof-row { display:flex; flex-direction:row; flex-wrap:wrap;",
                    "  align-items:flex-start; gap:8px; }",
                    // Base component styling: .kof-button/.kof-input/.kof-textarea/
                    // .kof-select had NO rule at all on this (live) runtime path —
                    // they rendered as bare native form controls (the static
                    // artifact-export path is the only place that styled them).
                    // Neutral defaults here so a Button/Input is a real, usable
                    // component out of the box; an app overrides look via
                    // Style/setBorder/setShadow/setGradient (inline style wins
                    // over these rules).
                    ".kof-view, .kof-button, .kof-input, .kof-textarea, .kof-select {",
                    "  box-sizing:border-box; }",
                    ".kof-button, .kof-input, .kof-textarea, .kof-select {",
                    "  font:inherit; color:inherit; font-size:15px; }",
                    ".kof-input, .kof-textarea, .kof-select {",
                    "  padding:10px 14px; border-radius:10px;",
                    "  border:1px solid rgba(0,0,0,.15); background:#fff; }",
                    ".kof-button {",
                    "  padding:12px 20px; border:none; border-radius:12px;",
                    "  background:#1f2937; color:#fff; font-weight:600; }",
                    // Interactive states: neutral (theme-agnostic) hover/focus/
                    // transition for the standard form/action widgets. brightness()
                    // reacts to whatever background an app sets via Style, so this
                    // stays correct across light/dark palettes; the focus ring uses
                    // a fixed accessible blue, the conventional cross-browser default.
                    ".kof-button, .kof-input, .kof-textarea, .kof-select, .kof-view {",
                    "  transition: box-shadow 180ms ease, transform 180ms ease,",
                    "    filter 180ms ease, border-color 180ms ease; }",
                    ".kof-button { cursor:pointer; }",
                    ".kof-button:hover:not(:disabled) { filter:brightness(1.06); transform:translateY(-1px); }",
                    ".kof-button:active:not(:disabled) { transform:translateY(0); filter:brightness(0.97); }",
                    ".kof-button:disabled { opacity:.6; cursor:not-allowed; }",
                    ".kof-input:focus, .kof-textarea:focus, .kof-select:focus {",
                    "  outline:none; border-color:#3b82f6;",
                    "  box-shadow:0 0 0 4px rgba(59,130,246,.18); }"
                ].join("\\n");
                (document.head || document.documentElement).appendChild(style);
            }

            export function kofUiWindowSetTitle(window, title) {
                if (typeof document !== "undefined") {
                    document.title = title;
                }
            }

            export function kofUiWindowTitle(window) {
                return typeof document !== "undefined" ? document.title : "";
            }

            export function kofUiWindowBind(win, label) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = globalThis.window && globalThis.window.__kofWindows
                        && globalThis.window.__kofWindows[win];
                if (!winEl) return;
                // Component Core: a component binds under the window and mounts
                // (view + onMount) — lifecycle is automatic.
                const comp = kofUiComponents.get(label);
                if (comp) {
                    if (comp.el) winEl.appendChild(comp.el);
                    kofUiComponentMount(label);
                    return;
                }
                const nodes = globalThis.window && globalThis.window.__kofNodes;
                const node = nodes && nodes[label];
                if (node) {
                    winEl.appendChild(node);
                }
            }

            export function kofUiWindowShow(window) {
                kofUiSerializeHtml();
            }

            export function kofUiWindowSetSize(window, width, height) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    winEl.style.width = width + "px";
                    winEl.style.height = height + "px";
                }
                try {
                    if (typeof window.resizeTo === "function") {
                        window.resizeTo(width, height);
                    }
                } catch (e) {
                    // resizeTo is blocked on some hosts; the CSS sizing above
                    // still constrains the window content.
                }
            }

            export function kofUiWindowClose(window) {
                if (typeof document === "undefined") {
                    return;
                }
                const winEl = window.__kofWindows && window.__kofWindows[window];
                if (winEl) {
                    if (winEl.parentNode) {
                        winEl.parentNode.removeChild(winEl);
                    }
                    delete window.__kofWindows[window];
                }
            }

            export function kofUiWindowSetTheme(window, theme) {
                if (typeof document === "undefined") {
                    return;
                }
                const root = document.getElementById("kof-root");
                if (!root) {
                    return;
                }
                const colors = theme
                        ? { background: 0x121212FF, text: 0xFFFFFFFF }
                        : { background: 0xFFFFFFFF, text: 0x000000FF };
                root.style.backgroundColor = kofUiColorToCss(colors.background);
                root.style.color = kofUiColorToCss(colors.text);
            }
            """;

}
